export const locations = [
  {
    province: {
      en: "Phnom Penh",
      kh: "ភ្នំពេញ",
    },
    districts: [
      {
        district: {
          en: "Doun Penh",
          kh: "ដូនពេញ",
        },
        communes: [
          { en: "Boeng Reang", kh: "បឹងរាំង" },
          { en: "Chaktomuk", kh: "ចតុមុខ" },
          { en: "Chey Chumneah", kh: "ជ័យជំនះ" },
          { en: "Phsar Chas", kh: "ផ្សារចាស់" },
          { en: "Phsar Kandal I", kh: "ផ្សារកណ្តាលទី១" },
          { en: "Phsar Kandal II", kh: "ផ្សារកណ្តាលទី២" },
          { en: "Phsar Thmei III", kh: "ផ្សារថ្មីទី៣" },
          { en: "Phsar Thmei I", kh: "ផ្សារថ្មីទី១" },
          { en: "Phsar Thmei II", kh: "ផ្សារថ្មីទី២" },
          { en: "Srah Chak", kh: "ស្រះចក" },
          { en: "Wat Phnom", kh: "វត្តភ្នំ" },
        ],
      },
      {
        district: {
          en: "Chamkarmon",
          kh: "ចំការមន",
        },
        communes: [
          { en: "", kh: "បឹងត្របែក" },
          { en: "", kh: "ផ្សារដើមថ្កូវ" },
          { en: "", kh: "ទួលទំពូងទី ១" },
          { en: "", kh: "ទួលទំពូងទី ២" },
        ],
      },
      {
        district: {
          en: "Boeng Keng Kang",
          kh: "បឹងកេងកង",
        },
        communes: [
          { en: "Boeng Keng Kang III", kh: "បឹងកេងកងទី ៣" },
          { en: "Boeng Keng Kang I", kh: "បឹងកេងកងទី ១" },
          { en: "Boeng Keng Kang II", kh: "បឹងកេងកងទី ២" },
          { en: "Olympic", kh: "អូឡាំពិក" },
          { en: "Tumnob Tuek", kh: "ទំនប់ទឹក" },
          { en: "Tuol Svay Prey I", kh: "ទួលស្វាយព្រៃទី ១" },
          { en: "Tuol Svay Prey II", kh: "ទួលស្វាយព្រៃទី ២" },
        ],
      },
      {
        district: {
          en: "Chbar Ampov",
          kh: "ច្បារអំពៅ",
        },
        communes: [
          { en: "Chbar Ampov I", kh: "ច្បារអំពៅទី ១" },
          { en: "Chbar Ampov II", kh: "ច្បារអំពៅទី ២" },
          { en: "Kbal Kaoh", kh: "ក្បាលកោះ" },
          { en: "Nirouth", kh: "និរោធ" },
          { en: "Prek Eng", kh: "ព្រែកឯង" },
          { en: "Prek Bra", kh: "ព្រែកប្រា" },
          { en: "Prek Thmei", kh: "ព្រែកថ្មី" },
          { en: "Veal Sbov", kh: "វាលស្បូវ" },
        ],
      },

      {
        district: {
          en: "Chroy Changvar",
          kh: "ជ្រោយចង្វារ",
        },
        communes: [
          { en: "Bak Khaeng", kh: "បាក់ខែង" },
          { en: "Chroy Changvar", kh: "ជ្រោយចង្វារ" },
          { en: "Kaoh Dach", kh: "កោះដាច់" },
          { en: "Prek Lieb", kh: "ព្រែកលៀប" },
          { en: "Prek Ta Sek", kh: "ព្រែកតាសេក" },
        ],
      },

      {
        district: {
          en: "Dangkao",
          kh: "ដង្កោ",
        },
        communes: [
          { en: "Cheung Ek", kh: "ជើងឯក" },
          { en: "Dangkao", kh: "ដង្កោ" },
          { en: "Kong Noy", kh: "គងនយ" },
          { en: "Krang Pongro", kh: "ក្រាំងពង្រ" },
          { en: "Pong Tuek", kh: "ពងទឹក" },
          { en: "Prek Kampues", kh: "ព្រែកកំពឹស" },
          { en: "Prey Sar", kh: "ព្រៃស" },
          { en: "Prey Veaeng", kh: "ព្រៃវែង" },
          { en: "Roluos", kh: "រលួស" },
          { en: "Sak Sampov", kh: "សាក់សំពៅ" },
          { en: "Spean Thma", kh: "ស្ពានថ្ម" },
          { en: "Teuk Thla", kh: "ទៀន" },
        ],
      },

      {
        district: {
          en: "Kamboul",
          kh: "កំបូល",
        },
        communes: [
          { en: "Boeng Thum", kh: "បឹងធំ" },
          { en: "Kamboul", kh: "កំបូល" },
          { en: "Kantouk", kh: "កន្ទោក" },
          { en: "Ou Laok", kh: "ឪឡោក" },
          { en: "Phleung Chheh Roteh", kh: "ភ្លើងឆេះរទេះ" },
          { en: "Prateah Lang", kh: "ប្រទះឡាង" },
          { en: "Snao", kh: "ស្នោ" },
        ],
      },

      {
        district: {
          en: "Mean Chey",
          kh: "មានជ័យ",
        },
        communes: [
          { en: "Boeng Tompun I", kh: "បឹងទំពុនទី១" },
          { en: "Boeng Tompun II", kh: "បឹងទំពុនទី២" },
          { en: "Chak Angrae Kraom", kh: "ចាក់អង្រែក្រោម" },
          { en: "Chak Angrae Leu", kh: "ចាក់អង្រែលើ" },
          { en: "Stueng Mean Chey I", kh: "ស្ទឹងមានជ័យទី១" },
          { en: "Stueng Mean Chey II", kh: "ស្ទឹងមានជ័យទី២" },
          { en: "Stueng Mean Chey III", kh: "ស្ទឹងមានជ័យទី៣" },
        ],
      },

      {
        district: {
          en: "Poipet",
          kh: "ពោធិសែនជ័យ",
        },
        communes: [
          { en: "Choam Chao I", kh: "ចោមចៅទី១" },
          { en: "Choam Chao II", kh: "ចោមចៅទី២" },
          { en: "Choam Chao III", kh: "ចោមចៅទី៣" },
          { en: "Kakab I", kh: "កាកាបទី១" },
          { en: "Kakab II", kh: "កាកាបទី២" },
          { en: "Samraong Kraom", kh: "សំរោងក្រោម" },
          { en: "Trepang Krasang", kh: "ត្រពាំងក្រសាំង" },
        ],
      },
      {
        district: {
          en: "7 Makara",
          kh: "៧មករា",
        },
        communes: [
          { en: "Boeng Pralit", kh: "បឹងព្រលឹត" },
          { en: "Mittapheap", kh: "មិត្ដភាព" },
          { en: "Manoram", kh: "មនោរម្យ" },
          { en: "Orussey III", kh: "អូរឫស្សីទី ៣" },
          { en: "Orussey IV", kh: "អូរឫស្សីទី ៤" },
          { en: "Orussey I", kh: "អូរឫស្សីទី ១" },
          { en: "Orussey II", kh: "អូរឫស្សីទី ២" },
          { en: "Veal Vong", kh: "វាលវង់" },
        ],
      },

      {
        district: {
          en: "Prek Phnov",
          kh: "ព្រែកព្នៅ",
        },
        communes: [
          { en: "Kok Roka", kh: "គោករកា" },
          { en: "Phnheav Phon", kh: "ពញាពន់" },
          { en: "Phonsang", kh: "ពន្សាំង" },
          { en: "Prek Phnov", kh: "ព្រែកព្នៅ" },
          { en: "Samraong", kh: "សំរោង" },
        ],
      },
      {
        district: {
          en: "Russei Keo",
          kh: "ឫស្សីកែវ",
        },
        communes: [
          { en: "Chrang Chamreh I", kh: "ច្រាំងចំរេះទី ១" },
          { en: "Chrang Chamreh II", kh: "ច្រាំងចំរេះទី ២" },
          { en: "Kilometer 6", kh: "គីឡូម៉ែត្រលេខ៦" },
          { en: "Russei Keo", kh: "ឫស្សីកែវ" },
          { en: "Svay Bak", kh: "ស្វាយប៉ាក" },
          { en: "Tuol Sangke I", kh: "ទួលសង្កែទី១" },
          { en: "Tuol Sangke II", kh: "ទួលសង្កែទី២" },
        ],
      },
      {
        district: {
          en: "Sensok",
          kh: "សែនសុខ",
        },
        communes: [
          { en: "Khmounh", kh: "ឃ្មួញ" },
          { en: "Kok Khleang", kh: "គោកឃ្លាង" },
          { en: "Krang Thnong", kh: "ក្រាំងធ្នង់" },
          { en: "Ou Baek Akam", kh: "អូរបែកក្អម" },
          { en: "Phnom Penh Thmei", kh: "ភ្នំពេញថ្មី" },
          { en: "Tuk Thla", kh: "ទឹកថ្លា" },
        ],
      },

      {
        district: {
          en: "Tuol Kork",
          kh: "ទួលគោក",
        },
        communes: [
          { en: "Boeng Kok I", kh: "បឹងកក់ទី ១" },
          { en: "Boeng Kok II", kh: "បឹងកក់ទី ២" },
          { en: "Boeng Salang", kh: "បឹងសាឡាង" },
          { en: "Phsar Derm Kor", kh: "ផ្សារដើមគរ" },
          { en: "Phsar Depo III", kh: "ផ្សារដេប៉ូទី ៣" },
          { en: "Phsar Depo I", kh: "ផ្សារដេប៉ូទី ១" },
          { en: "Phsar Depo II", kh: "ផ្សារដេប៉ូទី ២" },
          { en: "Tuk Lork III", kh: "ទឹកល្អក់ទី ៣" },
          { en: "Tuk Lork I", kh: "ទឹកល្អក់ទី ១" },
          { en: "Tuk Lork II", kh: "ទឹកល្អក់ទី ២" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Siem Reap",
      kh: "សៀមរាប",
    },
    districts: [
      {
        district: {
          en: "Angkor Chum",
          kh: "អង្គរជុំ",
        },
        communes: [
          { en: "Charchouk", kh: "ចារឈូក" },
          { en: "Doun Peng", kh: "ដូនពេង" },
          { en: "Kok Dong", kh: "គោកដូង" },
          { en: "Kol", kh: "គោល" },
          { en: "Nokor Phias", kh: "នគរភាស" },
          { en: "Srae Khvav", kh: "ស្រែខ្វាវ" },
          { en: "Tasam", kh: "តាសោម" },
        ],
      },
      {
        district: {
          en: "Angkor Thum",
          kh: "អង្គរធំ",
        },
        communes: [
          { en: "Chob Tat Raev", kh: "ជប់តាត្រាវ" },
          { en: "Liang Dai", kh: "លាងដៃ" },
          { en: "Peak Snaeng", kh: "ពាក់ស្នែង" },
          { en: "Svay Chek", kh: "ស្វាយចេក" },
        ],
      },
      {
        district: {
          en: "Banteay Srei",
          kh: "បន្ទាយស្រី",
        },
        communes: [
          { en: "Knar Sanday", kh: "ខ្នារសណ្ដាយ" },
          { en: "Khun Ream", kh: "ឃុនរាម" },
          { en: "Preah Dak", kh: "ព្រះដាក់" },
          { en: "Rum Chek", kh: "រំចេក" },
          { en: "Runt Ta Ek", kh: "រុនតាឯក" },
          { en: "Tbaeng", kh: "ត្បែង" },
        ],
      },
      {
        district: {
          en: "Chikreng",
          kh: "ជីក្រែង",
        },
        communes: [
          { en: "Anlong Samnar", kh: "អន្លង់សំណរ" },
          { en: "Chikreng", kh: "ជីក្រែង" },
          { en: "Kampong Kdei", kh: "កំពង់ក្ដី" },
          { en: "Khvav", kh: "ខ្វាវ" },
          { en: "Kok Thlok Kraom", kh: "គោកធ្លកក្រោម" },
          { en: "Kok Thlok Leu", kh: "គោកធ្លកលើ" },
          { en: "Lveang Russei", kh: "ល្វែងឫស្សី" },
          { en: "Pong Kroam", kh: "ពង្រក្រោម" },
          { en: "Pong Lve", kh: "ពង្រលើ" },
          { en: "Russei Lok", kh: "ឫស្សីលក" },
          { en: "Sangve", kh: "សង្វើយ" },
          { en: "Spian Tnot", kh: "ស្ពានត្នោត" },
        ],
      },

      {
        district: {
          en: "Kralanh",
          kh: "ក្រឡាញ់",
        },
        communes: [
          { en: "Chonlas Dai", kh: "ចន្លាសដៃ" },
          { en: "Kampong Thkov", kh: "កំពង់ថ្កូវ" },
          { en: "Kralanh", kh: "ក្រឡាញ់" },
          { en: "Krouch Kor", kh: "ក្រូចគរ" },
          { en: "Rong Ko", kh: "រោងគោ" },
          { en: "Sen Sok", kh: "សែនសុខ" },
          { en: "Sambour", kh: "សំបួរ" },
          { en: "Snaol", kh: "ស្នួល" },
          { en: "Sralal", kh: "ស្រណាល" },
          { en: "Ta An", kh: "តាអាន" },
        ],
      },
      {
        district: {
          en: "Siem Reap",
          kh: "សៀមរាប",
        },
        communes: [
          { en: "Ampil", kh: "អំពិល" },
          { en: "Chong Khneas", kh: "ចុងឃ្នៀស" },
          { en: "Chraev", kh: "ជ្រាវ" },
          { en: "Kok Chak", kh: "គោកចក" },
          { en: "Krabe Real", kh: "ក្របីរៀល" },
          { en: "Nokor Thum", kh: "នគរធំ" },
          { en: "Sala Komrerk", kh: "សាលាកំរើក" },
          { en: "Sambour", kh: "សំបួរ" },
          { en: "Siem Reap", kh: "សៀមរាប" },
          { en: "Slakram", kh: "ស្លក្រាម" },
          { en: "Srange", kh: "ស្រង៉ែ" },
          { en: "Svay Dangkum", kh: "ស្វាយដង្គំ" },
          { en: "Tuk Vil", kh: "ទឹកវិល" },
        ],
      },
      {
        district: {
          en: "Prasat Bakong",
          kh: "ប្រាសាទបាគង",
        },
        communes: [
          { en: "Bakong", kh: "បាគង" },
          { en: "Ballang", kh: "បល្ល័ង្គ" },
          { en: "Kampong Phluk", kh: "កំពង់ភ្លុក" },
          { en: "Kandek", kh: "កណ្ដែក" },
          { en: "Kantreang", kh: "កន្ទ្រាំង" },
          { en: "Mean Chey", kh: "មានជ័យ" },
          { en: "Roluos", kh: "រលួស" },
          { en: "Trepang Thum", kh: "ត្រពាំងធំ" },
        ],
      },
      {
        district: {
          en: "Pouk",
          kh: "ពួក",
        },
        communes: [
          { en: "Doun Keo", kh: "ដូនកែវ" },
          { en: "Keo Por", kh: "កែវពណ៌" },
          { en: "Kdey Run", kh: "ក្ដីរុន" },
          { en: "Knart", kh: "ខ្នាត" },
          { en: "Lvea", kh: "ល្វា" },
          { en: "Mouk Ban", kh: "មុខប៉ែន" },
          { en: "Pouth Tray", kh: "ពោធិ៍ទ្រាយ" },
          { en: "Prey Chouk", kh: "ព្រៃជ្រូក" },
          { en: "Pouk", kh: "ពួក" },
          { en: "Rul", kh: "រើល" },
          { en: "Samraong Ya", kh: "សំរោងយា" },
          { en: "Sasatham", kh: "សសរស្ដម្ភ" },
          { en: "Trei Nhe", kh: "ត្រីញ័រ" },
          { en: "Yeang", kh: "យាង" },
        ],
      },
      {
        district: {
          en: "Sot Nikum",
          kh: "សូទ្រនិគម",
        },
        communes: [
          { en: "Chan Sar", kh: "ចាន់ស" },
          { en: "Damdek", kh: "ដំដែក" },
          { en: "Dan Ron", kh: "ដានរុន" },
          { en: "Kampong Khleang", kh: "កំពង់ឃ្លាំង" },
          { en: "Khas", kh: "ខ្ចាស់" },
          { en: "Knart Pouth", kh: "ខ្នារពោធិ៍" },
          { en: "Kien Sangkae", kh: "កៀនសង្កែ" },
          { en: "Popeil", kh: "ពពេល" },
          { en: "Samraong", kh: "សំរោង" },
          { en: "Tayek", kh: "តាយ៉ែក" },
        ],
      },

      {
        district: {
          en: "Srei Sanam",
          kh: "ស្រីស្នំ",
        },
        communes: [
          { en: "Chroy Neang Ngoun", kh: "ជ្រោយនាងងួន" },
          { en: "Klang Hai", kh: "ក្លាំងហាយ" },
          { en: "Mong", kh: "មោង" },
          { en: "Prey", kh: "ប្រីយ៍" },
          { en: "Slang Spian", kh: "ស្លែងស្ពាន" },
          { en: "Tram Sasar", kh: "ត្រាំសសរ" },
        ],
      },
      {
        district: {
          en: "Svay Leu",
          kh: "ស្វាយលើ",
        },
        communes: [
          { en: "Bung Mela", kh: "បឹងមាលា" },
          { en: "Kantout", kh: "កន្ទួត" },
          { en: "Khnang Phnum", kh: "ខ្នងភ្នំ" },
          { en: "Svay Leu", kh: "ស្វាយលើ" },
          { en: "Ta Siem", kh: "តាសៀម" },
        ],
      },
      {
        district: {
          en: "Varin",
          kh: "វ៉ារិន",
        },
        communes: [
          { en: "Lvea Krang", kh: "ល្វាក្រាំង" },
          { en: "Prasat", kh: "ប្រាសាទ" },
          { en: "Srae Noy", kh: "ស្រែណូយ" },
          { en: "Svay S", kh: "ស្វាយស" },
          { en: "Varin", kh: "វ៉ារិន" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Battambang",
      kh: "បាត់ដំបង",
    },
    districts: [
      {
        district: {
          en: "Eak Phnom",
          kh: "ឯកភ្នំ",
        },
        communes: [
          { en: "Koh Jivang", kh: "កោះជីវាំង" },
          { en: "Peam Eak", kh: "ពាមឯក" },
          { en: "Prek Kphop", kh: "ព្រែកខ្ពប" },
          { en: "Prek Hluong", kh: "ព្រែកហ្លួង" },
          { en: "Prek Narinth", kh: "ព្រែកនរិន្ទ" },
          { en: "Prey Chas", kh: "ព្រៃចាស់" },
          { en: "Samrong Knong", kh: "សំរោងក្នុង" },
        ],
      },
      {
        district: {
          en: "Bannan",
          kh: "បាណន់",
        },
        communes: [
          { en: "Bay Damram", kh: "បាយដំរាំ" },
          { en: "Chaeng Mean Chey", kh: "ចែងមានជ័យ" },
          { en: "Chher Teal", kh: "ឈើទាល" },
          { en: "Kanteu 1", kh: "កន្ទឺ ១" },
          { en: "Kanteu 2", kh: "កន្ទឺ ២" },
          { en: "Phnom Sampov", kh: "ភ្នំសំពៅ" },
          { en: "Sneng", kh: "ស្នឹង" },
          { en: "Ta Kream", kh: "តាគ្រាម" },
        ],
      },
      {
        district: {
          en: "Bavel",
          kh: "បវេល",
        },
        communes: [
          { en: "Ampil Bram Daem", kh: "អំពិលប្រាំដើម" },
          { en: "Bavel", kh: "បវេល" },
          { en: "Kdol Ta Hen", kh: "ក្ដុលតាហែន" },
          { en: "Khnar Chormas", kh: "ខ្នាចរមាស" },
          { en: "Lvea", kh: "ល្វា" },
          { en: "Prey Kphov", kh: "ព្រៃខ្ពស់" },
        ],
      },
      {
        district: {
          en: "Kampong Reang",
          kh: "កំរៀង",
        },
        communes: [
          { en: "Bung Reang", kh: "បឹងរាំង" },
          { en: "Kampong Reang", kh: "កំរៀង" },
          { en: "O Da", kh: "អូរដា" },
          { en: "Ta Kri", kh: "តាក្រី" },
          { en: "Ta Sen", kh: "តាសែន" },
          { en: "Trang", kh: "ត្រាង" },
        ],
      },

      {
        district: {
          en: "Koh Kral",
          kh: "គាស់ក្រឡ",
        },
        communes: [
          { en: "Chhnal Morn", kh: "ឆ្នាល់មាន់" },
          { en: "Doun Ba", kh: "ដូនបា" },
          { en: "Hap", kh: "ហប់" },
          { en: "Koh Kral", kh: "គាស់ក្រឡ" },
          { en: "Preah Phos", kh: "ព្រះផុស" },
          { en: "Thipathai", kh: "ធិបតី" },
        ],
      },

      {
        district: {
          en: "Battambang",
          kh: "បាត់ដំបង",
        },
        communes: [
          { en: "Chomkar Samrong", kh: "ចំការសំរោង" },
          { en: "Kdol Doun Teav", kh: "ក្ដុលដូនទាវ" },
          { en: "O Chaar", kh: "អូរចារ" },
          { en: "O Mall", kh: "អូរម៉ាល់" },
          { en: "Prek Preah Sdech", kh: "ព្រែកព្រះស្ដេច" },
          { en: "Ratanak", kh: "រតនៈ" },
          { en: "Slakate", kh: "ស្លាកែត" },
          { en: "Svay Po", kh: "ស្វាយប៉ោ" },
          { en: "Toul Ta Ek", kh: "ទួលតាឯក" },
          { en: "Vattakhor", kh: "វត្ដគរ" },
        ],
      },
      {
        district: {
          en: "Mong Russei",
          kh: "មោងឫស្សី",
        },
        communes: [
          { en: "Chrai", kh: "ជ្រៃ" },
          { en: "Kakao", kh: "កកោះ" },
          { en: "Kea", kh: "គារ" },
          { en: "Mong", kh: "មោង" },
          { en: "Prey Svay", kh: "ព្រៃស្វាយ" },
          { en: "Prey Toch", kh: "ព្រៃតូច" },
          { en: "Roubas Mangal", kh: "របស់មង្គល" },
          { en: "Russei Krang", kh: "ឫស្សីក្រាំង" },
          { en: "Ta Las", kh: "តាលាស់" },
        ],
      },
      {
        district: {
          en: "Phnom Prek",
          kh: "ភ្នំព្រឹក",
        },
        communes: [
          { en: "Barang Thleak", kh: "បារាំងធ្លាក់" },
          { en: "Chakry", kh: "ចក្រី" },
          { en: "O Rumduol", kh: "អូររំដួល" },
          { en: "Pech Chinda", kh: "ពេជ្រចិន្ដា" },
          { en: "Phnom Prek", kh: "ភ្នំព្រឹក" },
        ],
      },
      {
        district: {
          en: "Ratanak Mondul",
          kh: "រតនមណ្ឌល",
        },
        communes: [
          { en: "Andeuk Haep", kh: "អណ្ដើកហែប" },
          { en: "Phlov Meas", kh: "ផ្លូវមាស" },
          { en: "Sdao", kh: "ស្ដៅ" },
          { en: "Traeng", kh: "ត្រែង" },
        ],
      },
      {
        district: {
          en: "Ruk Kiri",
          kh: "រុក្ខគិរី",
        },
        communes: [
          { en: "Prek Jeik", kh: "ព្រែកជីក" },
          { en: "Prey Tralach", kh: "ព្រៃត្រឡាច" },
        ],
      },
      {
        district: {
          en: "Samlot",
          kh: "សំឡូត",
        },
        communes: [
          { en: "Kampong Lpov", kh: "កំពង់ល្ពៅ" },
          { en: "Mean Chey", kh: "មានជ័យ" },
          { en: "O Sambuol", kh: "អូរសំរិល" },
          { en: "Samlot", kh: "សំឡូត" },
          { en: "Song", kh: "ស៊ុង" },
          { en: "Ta Sanh", kh: "តាសាញ" },
          { en: "Ta Tok", kh: "តាតោក" },
        ],
      },

      {
        district: {
          en: "Sampov Lun",
          kh: "សំពៅលូន",
        },
        communes: [
          { en: "Angkor Ban", kh: "អង្គរបាន" },
          { en: "Chrai Sima", kh: "ជ្រៃសីមា" },
          { en: "Sampov Lun", kh: "សំពៅលូន" },
          { en: "Santepheap", kh: "សន្ដិភាព" },
          { en: "Serei Mean Chey", kh: "សេរីមានជ័យ" },
          { en: "Ta Sda", kh: "តាស្ដា" },
        ],
      },

      {
        district: {
          en: "Sangke",
          kh: "សង្កែ",
        },
        communes: [
          { en: "Anlong Vil", kh: "អន្លង់វិល" },
          { en: "Kampong Preah", kh: "កំពង់ព្រះ" },
          { en: "Kampong Prey", kh: "កំពង់ព្រៀង" },
          { en: "Nora", kh: "នរា" },
          { en: "O Dambong 1", kh: "អូរដំបង ១" },
          { en: "O Dambong 2", kh: "អូរដំបង ២" },
          { en: "Rang Kesei", kh: "រាំងកេសី" },
          { en: "Roka", kh: "រកា" },
          { en: "Ta Pon", kh: "តាប៉ុន" },
          { en: "Vattakamim", kh: "វត្ដតាមិម" },
        ],
      },
      {
        district: {
          en: "Thma Kol",
          kh: "ថ្មគោល",
        },
        communes: [
          { en: "Anlong Roun", kh: "អន្លង់រុន" },
          { en: "Bansay Traeng", kh: "បន្សាយត្រែង" },
          { en: "Bung Pring", kh: "បឹងព្រីង" },
          { en: "Chrai", kh: "ជ្រៃ" },
          { en: "Chroy Sdao", kh: "ជ្រោយស្ដៅ" },
          { en: "Kok Khmum", kh: "គោកឃ្មុំ" },
          { en: "O Ta Ki", kh: "អូរតាគី" },
          { en: "Rung Chrai", kh: "រូងជ្រៃ" },
          { en: "Ta Men", kh: "តាម៉ឺន" },
          { en: "Ta Pong", kh: "តាពូង" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Preah Sihanouk",
      kh: "ព្រះសីហនុ",
    },
    districts: [
      {
        district: {
          en: "Kampong Seila",
          kh: "កំពង់សីលា",
        },
        communes: [
          { en: "Chamkar Luong", kh: "ចំការហ្លួង" },
          { en: "Kampong Seila", kh: "កំពង់សីលា" },
          { en: "Ouk Bak Roteh", kh: "អូរបាក់រទេះ" },
          { en: "Stung Chhay", kh: "ស្ទឹងឆាយ" },
        ],
      },

      {
        district: {
          en: "Kampong Som",
          kh: "កំពង់សោម",
        },
        communes: [
          { en: "Bitt Trang", kh: "បិតត្រាង" },
          { en: "Boeng Tapram", kh: "បឹងតាព្រហ្ម" },
          { en: "Ouk Jreav", kh: "អូរជ្រៅ" },
          { en: "Ouk Okhnhya Heng", kh: "អូរឧកញ៉ាហេង" },
          { en: "Raam", kh: "រាម" },
        ],
      },

      {
        district: {
          en: "Preah Sihanouk",
          kh: "ព្រះសីហនុ",
        },
        communes: [
          { en: "Koh Rong", kh: "កោះរ៉ុង" },
          { en: "Sangkat 3", kh: "សង្កាត់លេខ៣" },
          { en: "Sangkat 4", kh: "សង្កាត់លេខ៤" },
          { en: "Sangkat 1", kh: "លេខ១" },
          { en: "Sangkat 2", kh: "សង្កាត់លេខ២" },
        ],
      },

      {
        district: {
          en: "Prey Nob",
          kh: "ព្រៃនប់",
        },
        communes: [
          { en: "Andong Thma", kh: "អណ្ដូងថ្ម" },
          { en: "Cheung Ko", kh: "ជើងគោ" },
          { en: "Prey Nob", kh: "ព្រៃនប់" },
          { en: "Samaki", kh: "សាមគ្គី" },
          { en: "Samrong", kh: "សំរុង" },
          { en: "Tuk Leak", kh: "ទឹកល្អក់" },
          { en: "Tuk Thla", kh: "ទឹកថ្លា" },
          { en: "Toul Totung", kh: "ទួលទទឹង" },
          { en: "Veal Renh", kh: "វាលរេញ" },
        ],
      },

      {
        district: {
          en: "Stueng Hav",
          kh: "ស្ទឹងហាវ",
        },
        communes: [
          { en: "Kampeng", kh: "កាមួយ" },
          { en: "O Treas", kh: "អូរត្រេះ" },
          { en: "Tumnob Rolok", kh: "ទំនប់រលក" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Kampong Cham",
      kh: "កំពង់ចាម",
    },
    districts: [
      {
        district: {
          en: "Batheay",
          kh: "បាធាយ",
        },
        communes: [
          { en: "Batheay", kh: "បាធាយ" },
          { en: "Chbar Ampov", kh: "ច្បារអំពៅ" },
          { en: "Chila", kh: "ជាលា" },
          { en: "Cheung Prey", kh: "ជើងព្រៃ" },
          { en: "Mepreing", kh: "មេព្រីង" },
          { en: "Phav", kh: "ផ្អាវ" },
          { en: "Sambo", kh: "សំបូរ" },
          { en: "Sandek", kh: "សណ្ដែក" },
          { en: "Tangkrang", kh: "តាំងក្រាំង" },
          { en: "Tangkrang Krasang", kh: "តាំងក្រសាំង" },
          { en: "Trab", kh: "ត្រប់" },
          { en: "Tumnob", kh: "ទំនប់" },
        ],
      },
      {
        district: {
          en: "Chamkar Leu",
          kh: "ចំការលើ",
        },
        communes: [
          { en: "Bos Knor", kh: "បុសខ្នុរ" },
          { en: "Chamkar Andoung", kh: "ចំការអណ្ដូង" },
          { en: "Chayo", kh: "ជយោ" },
          { en: "Lve Leu", kh: "ល្វាលើ" },
          { en: "Speu", kh: "ស្ពឺ" },
          { en: "Svay Tep", kh: "ស្វាយទាប" },
          { en: "Ta Ong", kh: "តាអុង" },
          { en: "Ta Brok", kh: "តាប្រុក" },
        ],
      },
      {
        district: {
          en: "Cheung Prey",
          kh: "ជើងព្រៃ",
        },
        communes: [
          { en: "Knor Dombong", kh: "ខ្នុរដំបង" },
          { en: "Koak Rovieng", kh: "គោករវៀង" },
          { en: "Phdao Jum", kh: "ផ្ដៅជុំ" },
          { en: "Prey Char", kh: "ព្រៃចារ" },
          { en: "Preing Chrum", kh: "ព្រីងជ្រុំ" },
          { en: "Sampong Chey", kh: "សំពងជ័យ" },
          { en: "Steung Chey", kh: "ស្ដើងជ័យ" },
          { en: "Sotevip", kh: "សូទិព្វ" },
          { en: "Samor", kh: "ស្រម៉រ" },
          { en: "Trapeang Kor", kh: "ត្រពាំងគរ" },
        ],
      },
      {
        district: {
          en: "Kampong Siem",
          kh: "កំពង់សៀម",
        },
        communes: [
          { en: "Ampil", kh: "អំពិល" },
          { en: "Han Chey", kh: "ហាន់ជ័យ" },
          { en: "Koh Mit", kh: "កោះមិត្ដ" },
          { en: "Koh Roka", kh: "កោះរកា" },
          { en: "Koh Samrong", kh: "កោះសំរោង" },
          { en: "Koh Tontem", kh: "កោះទន្ទឹម" },
          { en: "Kien Chrey", kh: "កៀនជ្រៃ" },
          { en: "Kokor", kh: "គគរ" },
          { en: "Krala", kh: "ក្រឡា" },
          { en: "Ousvay", kh: "អូរស្វាយ" },
          { en: "Raang", kh: "រអាង" },
          { en: "Rumchek", kh: "រំចេក" },
          { en: "Srok", kh: "ស្រក" },
          { en: "Tran", kh: "ទ្រាន" },
          { en: "Vihara Thom", kh: "វិហារធំ" },
        ],
      },
      {
        district: {
          en: "Kang Meas",
          kh: "កងមាស",
        },
        communes: [
          { en: "Angkor Ban", kh: "អង្គរបាន" },
          { en: "Kang Ta Nung", kh: "កងតាណឹង" },
          { en: "Khcheav", kh: "ខ្ចៅ" },
          { en: "Pham Chikang", kh: "ពាមជីកង" },
          { en: "Prek Kouy", kh: "ព្រែកកុយ" },
          { en: "Prek Krabaov", kh: "ព្រែកក្របៅ" },
          { en: "Raay Pai", kh: "រាយប៉ាយ" },
          { en: "Roka Ar", kh: "រកាអារ" },
          { en: "Roka Koy", kh: "រកាគយ" },
          { en: "Steav", kh: "ស្ដៅ" },
          { en: "Sor Kong", kh: "សូរគង" },
        ],
      },
      {
        district: {
          en: "Koh Soutin",
          kh: "កោះសូទិន",
        },
        communes: [
          { en: "Kampong Reap", kh: "កំពង់រាប" },
          { en: "Koh Soutin", kh: "កោះសូទិន" },
          { en: "Lve", kh: "ល្វេ" },
          { en: "Maha Khnuong", kh: "មហាខ្ញូង" },
          { en: "Maha Lap", kh: "មហាលាភ" },
          { en: "Pham Prethnuh", kh: "ពាមប្រធ្នោះ" },
          { en: "Prang", kh: "ពង្រ" },
          { en: "Prek Tanan", kh: "ព្រែកតានង់" },
        ],
      },
      {
        district: {
          en: "Kampong Cham",
          kh: "កំពង់ចាម",
        },
        communes: [
          { en: "Beung Kok", kh: "បឹងកុក" },
          { en: "Kampong Cham", kh: "កំពង់ចាម" },
          { en: "Sambo Meas", kh: "សំបួរមាស" },
          { en: "Veal Vong", kh: "វាលវង់" },
        ],
      },
      {
        district: {
          en: "Prey Chho",
          kh: "ព្រៃឈរ",
        },
        communes: [
          { en: "Baray", kh: "បារាយណ៍" },
          { en: "Beung Nay", kh: "បឹងណាយ" },
          { en: "Chrai Vien", kh: "ជ្រៃវៀន" },
          { en: "Kvit Thum", kh: "ខ្វិតធំ" },
          { en: "Kor", kh: "គរ" },
          { en: "Krouch", kh: "ក្រូច" },
          { en: "Lve", kh: "ល្វា" },
          { en: "Mien", kh: "មៀន" },
          { en: "Prey Chhor", kh: "ព្រៃឈរ" },
          { en: "Samrong", kh: "សំរោង" },
          { en: "Sory Sen", kh: "សូរ្យសែន" },
          { en: "Sram", kh: "ស្រង៉ែ" },
          { en: "Thma Poun", kh: "ថ្មពូន" },
          { en: "Tong Rong", kh: "តុងរ៉ុង" },
          { en: "Trapeang Preah", kh: "ត្រពាំងព្រះ" },
        ],
      },
      {
        district: {
          en: "Srey Santhor",
          kh: "ស្រីសន្ទរ",
        },
        communes: [
          { en: "Baray", kh: "បារាយណ៍" },
          { en: "Jibal", kh: "ជីបាល" },
          { en: "Koh Andet", kh: "កោះអណ្ដែត" },
          { en: "Khnears", kh: "ខ្នារស" },
          { en: "Mean Chey", kh: "មានជ័យ" },
          { en: "Prang Yam", kh: "ប្រាំយ៉ាម" },
          { en: "Prek Dambok", kh: "ព្រែកដំបូក" },
          { en: "Prek Pho", kh: "ព្រែកពោធិ" },
          { en: "Prek Rumdeng", kh: "ព្រែករំដេង" },
          { en: "Pteah Kandal", kh: "ផ្ទះកណ្ដាល" },
          { en: "Rassi Srok", kh: "ឫស្សីស្រុក" },
          { en: "Svay Po", kh: "ស្វាយពោធិ" },
          { en: "Svay Khsach Phnum", kh: "ស្វាយខ្សាច់ភ្នំ" },
          { en: "Tongtralach", kh: "ទងត្រឡាច" },
        ],
      },
      {
        district: {
          en: "Steung Trang",
          kh: "ស្ទឹងត្រង់",
        },
        communes: [
          { en: "Arak Tonat", kh: "អារក្សត្នោត" },
          { en: "Dang Kdar", kh: "ដងក្ដារ" },
          { en: "Kep Batang", kh: "ខ្ពបតាងួន" },
          { en: "Mesar Chrai", kh: "មេសរជ្រៃ" },
          { en: "Oum Lou", kh: "អូរម្លូ" },
          { en: "Pham Koh Sna", kh: "ពាមកោះស្នា" },
          { en: "Prek Bak", kh: "ព្រែកបាក់" },
          { en: "Prek Kouk", kh: "ព្រែកកក់" },
          { en: "Preah Andoung", kh: "ព្រះអណ្ដូង" },
          { en: "Sophias", kh: "សូភាស" },
          { en: "Toul Preah Khlang", kh: "ទួលព្រះឃ្លាំង" },
          { en: "Toul Sambour", kh: "ទួលសំបួរ" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Kandal",
      kh: "កណ្តាល",
    },
    districts: [
      {
        district: {
          en: "Angkor Snuol",
          kh: "អង្គស្នួល",
        },
        communes: [
          { en: "Baeck Chan", kh: "បែកចាន" },
          { en: "Chok Chheurng Neang", kh: "ឆក់ឈើនាង" },
          { en: "Damnak Ampil", kh: "ដំណាក់អំពិល" },
          { en: "Krang Makk", kh: "ក្រាំងម្កាក់" },
          { en: "Lomhach", kh: "លំហាច" },
          { en: "Makk", kh: "ម្កាក់" },
          { en: "Peuk", kh: "ពើក" },
          { en: "Prei Pouch", kh: "ព្រៃពួច" },
          { en: "Samrong Leu", kh: "សំរោងលើ" },
          { en: "Toul Prech", kh: "ទួលព្រេជ" },
        ],
      },
      {
        district: {
          en: "Kandal Steung",
          kh: "កណ្ដាលស្ទឹង",
        },
        communes: [
          { en: "Ampov Prey", kh: "អំពៅព្រៃ" },
          { en: "Anlong Ramiat", kh: "អន្លង់រមៀត" },
          { en: "Bar Koo", kh: "បារគូ" },
          { en: "Beung Khyang", kh: "បឹងខ្យាង" },
          { en: "Cheung Kerb", kh: "ជើងកើប" },
          { en: "Daem Ros", kh: "ដើមឫស" },
          { en: "Kandoak", kh: "កណ្ដោក" },
          { en: "Kok Trap", kh: "គោកត្រប់" },
          { en: "Prek Roka", kh: "ព្រែករកា" },
          { en: "Prek Sleng", kh: "ព្រែកស្លែង" },
          { en: "Preah Budd", kh: "ព្រះពុទ្ធ" },
          { en: "Roka", kh: "រកា" },
          { en: "Rolang Kan", kh: "រលាំងកែន" },
          { en: "Siem Reap", kh: "សៀមរាប" },
          { en: "Tbaeng", kh: "ត្បែង" },
          { en: "Thmey", kh: "ថ្មី" },
          { en: "Trapang Veng", kh: "ត្រពាំងវែង" },
          { en: "Trea", kh: "ទ្រា" },
        ],
      },
      {
        district: {
          en: "Koh Thum",
          kh: "កោះធំ",
        },
        communes: [
          { en: "Kampong Kong", kh: "កំពង់កុង" },
          { en: "Koh Thum A", kh: "កោះធំ ‹ក›" },
          { en: "Koh Thum B", kh: "កោះធំ ‹ខ›" },
          { en: "Lek Daek", kh: "លើកដែក" },
          { en: "Phuoth Ban", kh: "ពោធិ៍បាន" },
          { en: "Prek Thmei", kh: "ព្រែកថ្មី" },
        ],
      },
      {
        district: {
          en: "Khsach Kandal",
          kh: "ខ្សាច់កណ្ដាល",
        },
        communes: [
          { en: "Chey Thum", kh: "ជ័យធំ" },
          { en: "Kampong Chamlong", kh: "កំពង់ចំលង" },
          { en: "Koh Choram", kh: "កោះចូរ៉ាម" },
          { en: "Prek Tamak", kh: "ព្រែកតាមាក់" },
          { en: "Preah Brorsab", kh: "ព្រះប្រសប់" },
          { en: "Puk Ruessey", kh: "ពុកឫស្សី" },
          { en: "Roka Jangleng", kh: "រកាជន្លឹង" },
          { en: "Sanlong", kh: "សន្លុង" },
          { en: "Si Thor", kh: "ស៊ីធរ" },
          { en: "Svay Romiet", kh: "ស្វាយរមៀត" },
          { en: "Tae Ek", kh: "តាឯក" },
          { en: "Vihar Suor", kh: "វិហារសួគ៌" },
        ],
      },
      {
        district: {
          en: "Kien Svay",
          kh: "កៀនស្វាយ",
        },
        communes: [
          { en: "Banteay Dek", kh: "បន្ទាយដែក" },
          { en: "Cheur Teal", kh: "ឈើទាល" },
          { en: "Dey Iddah", kh: "ដីឥដ្ឋ" },
          { en: "Kampong Svay", kh: "កំពង់ស្វាយ" },
          { en: "Kok Kea", kh: "គគីរ" },
          { en: "Kok Thom", kh: "គគីធំ" },
          { en: "Phumi Thom", kh: "ភូមិធំ" },
          { en: "Samrong Thom", kh: "សំរោងធំ" },
        ],
      },
      {
        district: {
          en: "Krang Thkov",
          kh: "ក្រុងអរិយក្សត្រ",
        },
        communes: [
          { en: "Ariyaksat", kh: "អរិយក្សត្រ" },
          { en: "Back Dav", kh: "បាក់ដាវ" },
          { en: "Barong", kh: "បារុង" },
          { en: "Koh Uknya Ti", kh: "កោះឧកញ៉ាតី" },
          { en: "Prek Uknya Ong", kh: "ពាមឧកញ៉ាអុង" },
          { en: "Prek Ampil", kh: "ព្រែកអំពិល" },
          { en: "Prek Khmeng", kh: "ព្រែកក្មេង" },
          { en: "Prek Luong", kh: "ព្រែកហ្លួង" },
          { en: "Prek Takov", kh: "ព្រែកតាកូវ" },
          { en: "Sarika Kaev", kh: "សារិកាកែវ" },
          { en: "Svay Chrum", kh: "ស្វាយជ្រុំ" },
        ],
      },
      {
        district: {
          en: "Krang Smpov",
          kh: "ក្រុងសំពៅពូន",
        },
        communes: [
          { en: "Chher Khmao", kh: "ឈើខ្មៅ" },
          { en: "Chroy Takav", kh: "ជ្រោយតាកែវ" },
          { en: "Prek Chrei", kh: "ព្រែកជ្រៃ" },
          { en: "Prek Sdei", kh: "ព្រែកស្ដី" },
          { en: "Sampeau Poan", kh: "សំពៅពូន" },
        ],
      },
      {
        district: {
          en: "Ta Khmao",
          kh: "តាខ្មៅ",
        },
        communes: [
          { en: "Daem Mein", kh: "ដើមមៀន" },
          { en: "Kampong Samnang", kh: "កំពង់សំណាញ់" },
          { en: "Prek Hor", kh: "ព្រែកហូរ" },
          { en: "Prek Ruessey", kh: "ព្រែកឫស្សី" },
          { en: "Takdol", kh: "តាក្ដុល" },
          { en: "Ta Khmao", kh: "តាខ្មៅ" },
        ],
      },
      {
        district: {
          en: "Lek Daek",
          kh: "លើកដែក",
        },
        communes: [
          { en: "Kam Samnang", kh: "ក្អមសំណរ" },
          { en: "Kampong Phnum", kh: "កំពង់ភ្នំ" },
          { en: "Khab Ak Thav", kh: "ខ្ពបអាទាវ" },
          { en: "Peam Reang", kh: "ពាមរាំង" },
          { en: "Prek Dach", kh: "ព្រែកដាច់" },
          { en: "Prek Tonlab", kh: "ព្រែកទន្លាប់" },
          { en: "Sanda", kh: "សណ្ដារ" },
        ],
      },
      {
        district: {
          en: "Lvea Em",
          kh: "ល្វាឯម",
        },
        communes: [
          { en: "Beung Krom", kh: "បឹងគ្រំ" },
          { en: "Koh Kaev", kh: "កោះកែវ" },
          { en: "Koh Rase", kh: "កោះរះ" },
          { en: "Lveasara", kh: "ល្វាសរ" },
          { en: "Phumi Thom", kh: "ភូមិធំ" },
          { en: "Prek Rai", kh: "ព្រែករៃ" },
          { en: "Prek Ruessey", kh: "ព្រែកឫស្សី" },
          { en: "Sambuor", kh: "សំបួរ" },
          { en: "Thma Kor", kh: "ថ្មគរ" },
          { en: "Tuk Khlang", kh: "ទឹកឃ្លាំង" },
        ],
      },
      {
        district: {
          en: "Mok Kampul",
          kh: "មុខកំពូល",
        },
        communes: [
          { en: "Prek Anchanh", kh: "ព្រែកអញ្ចាញ" },
          { en: "Prek Dombang", kh: "ព្រែកដំបង" },
          { en: "Roka Kaong 1", kh: "រកាកោង ១" },
          { en: "Roka Kaong 2", kh: "រកាកោង ២" },
          { en: "Ruessey Chroy", kh: "ឫស្សីជ្រោយ" },
          { en: "Sambuor Meas", kh: "សំបួរមាស" },
          { en: "Svay Ampo", kh: "ស្វាយអំពារ" },
        ],
      },
      {
        district: {
          en: "Phnheak",
          kh: "ពញាឮ",
        },
        communes: [
          { en: "Chveang", kh: "ឈ្វាំង" },
          { en: "Chrei Les", kh: "ជ្រៃលាស់" },
          { en: "Kampong Hluong", kh: "កំពង់ហ្លួង" },
          { en: "Kampong Os", kh: "កំពង់អុស" },
          { en: "Koh Chin", kh: "កោះចិន" },
          { en: "Phnum Bat", kh: "ភ្នំបាត" },
          { en: "Phsar Daek", kh: "ផ្សារដែក" },
          { en: "Phnheak", kh: "ពញាឮ" },
          { en: "Prek Ta Ten", kh: "ព្រែកតាទែន" },
          { en: "Tumnob Thum", kh: "ទំនប់ធំ" },
          { en: "Vihar Luong", kh: "វិហារលួង" },
        ],
      },
      {
        district: {
          en: "Saang",
          kh: "ស្អាង",
        },
        communes: [
          { en: "Koh Anlong Chin", kh: "កោះអន្លង់ចិន" },
          { en: "Koh Khel", kh: "កោះខែល" },
          { en: "Koh Kasat Tnla", kh: "កោះខ្សាច់ទន្លា" },
          { en: "Khab", kh: "ខ្ពប" },
          { en: "Krang Yov", kh: "ក្រាំងយ៉ូវ" },
          { en: "Prasat", kh: "ប្រាសាទ" },
          { en: "Prek Ambil", kh: "ព្រែកអំបិល" },
          { en: "Prek Kouy", kh: "ព្រែកកុយ" },
          { en: "Roka Khpos", kh: "រកាខ្ពស់" },
          { en: "Saang Phnum", kh: "ស្អាងភ្នំ" },
          { en: "Sitbo", kh: "សិត្បូ" },
          { en: "Svay Pratal", kh: "ស្វាយប្រទាល" },
          { en: "Svay Rolum", kh: "ស្វាយរលំ" },
          { en: "Talon", kh: "តាលន់" },
          { en: "Truoy Sla", kh: "ត្រើយស្លា" },
          { en: "Tuk Vil", kh: "ទឹកវិល" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Banteay Meanchey",
      kh: "បន្ទាយមានជ័យ",
    },
    districts: [
      {
        district: { en: "Poi Pet", kh: "ក្រុងប៉ោយប៉ែត" },
        communes: [
          { en: "Nimit", kh: "និមិត្ដ" },
          { en: "Poi Pet", kh: "ប៉ោយប៉ែត" },
        ],
      },
      {
        district: { en: "Serei Sophorn", kh: "សិរីសោភ័ណ" },
        communes: [
          { en: "Kampong Svay", kh: "កំពង់ស្វាយ" },
          { en: "Koh Pong Satv", kh: "កោះពងសត្វ" },
          { en: "Makak", kh: "ម្កាក់" },
          { en: "O Ambel", kh: "អូរអំបិល" },
          { en: "Phnhiat", kh: "ភ្នៀត" },
          { en: "Preah Ponlea", kh: "ព្រះពន្លា" },
          { en: "Teuk Thla", kh: "ទឹកថ្លា" },
        ],
      },
      {
        district: { en: "Malai", kh: "ម៉ាឡៃ" },
        communes: [
          { en: "Beng Beng", kh: "បឹងបេង" },
          { en: "Malai", kh: "ម៉ាឡៃ" },
          { en: "O Sampor", kh: "អូរសំព័រ" },
          { en: "O Sralau", kh: "អូរស្រឡៅ" },
          { en: "Takong", kh: "តាគង់" },
          { en: "Tuol Pongro", kh: "ទួលពង្រ" },
        ],
      },
      {
        district: { en: "Mongkol Borei", kh: "មង្គលបូរី" },
        communes: [
          { en: "Banteay Neang", kh: "បន្ទាយនាង" },
          { en: "Batt Trang", kh: "បត់ត្រង់" },
          { en: "Chamnoy", kh: "ចំណោម" },
          { en: "Koak Ballang", kh: "គោកបល្ល័ង្គ" },
          { en: "Kuymang", kh: "គយម៉ែង" },
          { en: "O Brasat", kh: "អូរប្រាសាទ" },
          { en: "Phnom Toch", kh: "ភ្នំតូច" },
          { en: "Rahat Teuk", kh: "រហាត់ទឹក" },
          { en: "Rassi Kroak", kh: "ឫស្សីក្រោក" },
          { en: "Sambour", kh: "សំបួរ" },
          { en: "Seo", kh: "សឿ" },
          { en: "Srah Reang", kh: "ស្រះរាំង" },
          { en: "Ta Lom", kh: "តាឡំ" },
        ],
      },
      {
        district: { en: "O Chrov", kh: "អូរជ្រៅ" },
        communes: [
          { en: "Changha", kh: "ចង្ហា" },
          { en: "Kop", kh: "កូប" },
          { en: "Kuth Sat", kh: "គុត្ដសត" },
          { en: "O Bei Jan", kh: "អូរបីជាន់" },
          { en: "Samrong", kh: "សំរោង" },
          { en: "Singh", kh: "សឹង្ហ" },
          { en: "Sophi", kh: "សូភី" },
        ],
      },
      {
        district: { en: "Phnom Srok", kh: "ភ្នំស្រុក" },
        communes: [
          { en: "Nam Tav", kh: "ណាំតៅ" },
          { en: "Poi Chea", kh: "ប៉ោយចារ" },
          { en: "Phnom Dei", kh: "ភ្នំដី" },
          { en: "Ponlei", kh: "ពន្លៃ" },
          { en: "Spean Sraeng", kh: "ស្ពានស្រែង" },
          { en: "Srah Jeik", kh: "ស្រះជីក" },
        ],
      },
      {
        district: { en: "Preah Net Preah", kh: "ព្រះនេត្រព្រះ" },
        communes: [
          { en: "Bussobov", kh: "បុស្បូវ" },
          { en: "Chhnor Mean Chey", kh: "ឈ្នួរមានជ័យ" },
          { en: "Chob Varey", kh: "ជប់វារី" },
          { en: "Phnom Liep", kh: "ភ្នំលៀប" },
          { en: "Prasat", kh: "ប្រាសាទ" },
          { en: "Preah Net Preah", kh: "ព្រះនេត្រព្រះ" },
          { en: "Rahall", kh: "រហាល" },
          { en: "Tean Kam", kh: "ទានកាំ" },
          { en: "Teuk Chor", kh: "ទឹកជោរ" },
        ],
      },
      {
        district: { en: "Svay Chek", kh: "ស្វាយចេក" },
        communes: [
          { en: "Phkam", kh: "ផ្គាំ" },
          { en: "Rolouas", kh: "រលួស" },
          { en: "Sang", kh: "សារង្គ" },
          { en: "Slekram", kh: "ស្លក្រាម" },
          { en: "Svay Chek", kh: "ស្វាយចេក" },
          { en: "Taben", kh: "តាបែន" },
          { en: "Tapho", kh: "តាផូ" },
          { en: "Tresh", kh: "ត្រេះ" },
        ],
      },
      {
        district: { en: "Thma Puok", kh: "ថ្មពួក" },
        communes: [
          { en: "Banteay Chmar", kh: "បន្ទាយឆ្មារ" },
          { en: "Koak Khtin", kh: "គោកកឋិន" },
          { en: "Koak Romiet", kh: "គោករមៀត" },
          { en: "Kumrou", kh: "គំរូ" },
          { en: "Phum Thmei", kh: "ភូមិថ្មី" },
          { en: "Thma Puok", kh: "ថ្មពួក" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Kampong Chnang",
      kh: "កំពង់ឆ្នាំង",
    },
    districts: [
      {
        district: { en: "Baribour", kh: "បរិបូណ៌" },
        communes: [
          { en: "Anchanrung", kh: "អញ្ចាញរូង" },
          { en: "Chak", kh: "ចក" },
          { en: "Chhnouk Tro", kh: "ឆ្នុកទ្រូ" },
          { en: "Kampong Preah Kokir", kh: "កំពង់ព្រះគគីរ" },
          { en: "Kon Rong", kh: "ខុនរ៉ង" },
          { en: "Melom", kh: "មេលំ" },
          { en: "Pech Changvar", kh: "ពេជចង្វារ" },
          { en: "Phsar", kh: "ផ្សារ" },
          { en: "Ponlei", kh: "ពន្លៃ" },
          { en: "Papel", kh: "ពពេល" },
          { en: "Trepang Chan", kh: "ត្រពាំងចាន់" },
        ],
      },
      {
        district: { en: "Jal Kiri", kh: "ជលគីរី" },
        communes: [
          { en: "Jal Sa", kh: "ជលសា" },
          { en: "Kampong Os", kh: "កំពង់អុស" },
          { en: "Koh Thkov", kh: "កោះថ្កូវ" },
          { en: "Pham Chkoak", kh: "ពាមឆ្កោក" },
          { en: "Prey Kri", kh: "ព្រៃគ្រី" },
        ],
      },
      {
        district: { en: "Kampong Leng", kh: "កំពង់លែង" },
        communes: [
          { en: "Chra Nok", kh: "ច្រណូក" },
          { en: "Dar", kh: "ដារ" },
          { en: "Kampong Haov", kh: "កំពង់ហៅ" },
          { en: "Phlov Tuk", kh: "ផ្លូវទូក" },
          { en: "Poth", kh: "ពោធិ៍" },
          { en: "Prey Meas", kh: "ប្រឡាយមាស" },
          { en: "Samrong Sen", kh: "សំរោងសែន" },
          { en: "Svay Rompear", kh: "ស្វាយរំពារ" },
          { en: "Trengil", kh: "ត្រងិល" },
        ],
      },
      {
        district: { en: "Kampong Tralach", kh: "កំពង់ត្រឡាច" },
        communes: [
          { en: "Ampil Tek", kh: "អំពិលទឹក" },
          { en: "Chouk S", kh: "ឈូកស" },
          { en: "Chres", kh: "ច្រេស" },
          { en: "Kampong Tralach", kh: "កំពង់ត្រឡាច" },
          { en: "Longvek", kh: "លង្វែក" },
          { en: "O Rassi", kh: "អូរឫស្សី" },
          { en: "Peani", kh: "ពានី" },
          { en: "Saeb", kh: "សែប" },
          { en: "Tajes", kh: "តាជេស" },
          { en: "Thma Idth", kh: "ថ្មឥដ្ឋ" },
        ],
      },
      {
        district: { en: "Kampong Chhnang", kh: "កំពង់ឆ្នាំង" },
        communes: [
          { en: "Kampong Chhnang", kh: "កំពង់ឆ្នាំង" },
          { en: "Khsam", kh: "ខ្សាម" },
          { en: "Baer", kh: "ប្អេរ" },
          { en: "Phsar Chhnang", kh: "ផ្សារឆ្នាំង" },
        ],
      },
      {
        district: { en: "Rolapear", kh: "រលាប្អៀរ" },
        communes: [
          { en: "Andoung Sna", kh: "អណ្ដូងស្នាយ" },
          { en: "Banteay Preal", kh: "បន្ទាយព្រាល" },
          { en: "Cheung Krav", kh: "ជើងគ្រាវ" },
          { en: "Chrey Bak", kh: "ជ្រៃបាក់" },
          { en: "Koak Banteay", kh: "គោកបន្ទាយ" },
          { en: "Krang Leav", kh: "ក្រាំងលាវ" },
          { en: "Pong", kh: "ពង្រ" },
          { en: "Prosnub", kh: "ប្រស្នឹប" },
          { en: "Prey Mool", kh: "ព្រៃមូល" },
          { en: "Rolapear", kh: "រលាប្អៀរ" },
          { en: "Srae Thmei", kh: "ស្រែថ្មី" },
          { en: "Svay Jrum", kh: "ស្វាយជ្រុំ" },
          { en: "Teuk Hot", kh: "ទឹកហូត" },
        ],
      },
      {
        district: { en: "Samakki Mean Chey", kh: "សាមគ្គីមានជ័យ" },
        communes: [
          { en: "Chean Laeung", kh: "ឈានឡើង" },
          { en: "Khna Chmar", kh: "ខ្នារឆ្មារ" },
          { en: "Krang Lvea", kh: "ក្រាំងល្វា" },
          { en: "Pham", kh: "ពាម" },
          { en: "Sethe", kh: "សេដ្ឋី" },
          { en: "Svay", kh: "ស្វាយ" },
          { en: "Svay Juk", kh: "ស្វាយជុក" },
          { en: "Tbaeng Kphos", kh: "ត្បែងខ្ពស់" },
          { en: "Thlok Vien", kh: "ធ្លកវៀន" },
        ],
      },
      {
        district: { en: "Teuk Phos", kh: "ទឹកផុស" },
        communes: [
          { en: "Apivath", kh: "អភិវឌ្ឍន៍" },
          { en: "Chao Maung", kh: "ចោងម៉ោង" },
          { en: "Cheab", kh: "ជៀប" },
          { en: "Kbal Teuk", kh: "ក្បាលទឹក" },
          { en: "Klong Popak", kh: "ខ្លុងពពក" },
          { en: "Krang Skar", kh: "ក្រាំងស្គារ" },
          { en: "Tang Krasang", kh: "តាំងក្រសាំង" },
          { en: "Tuol Kphos", kh: "ទួលខ្ពស់" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Kampong Speu",
      kh: "កំពង់ស្ពឺ",
    },
    districts: [
      {
        district: { en: "Aoral", kh: "ឱរ៉ាល់" },
        communes: [
          { en: "Hong Samnang", kh: "ហោងសំណំ" },
          { en: "Rasmey Samaki", kh: "រស្មីសាមគ្គី" },
          { en: "Sangke Satap", kh: "សង្កែសាទប" },
          { en: "Tasal", kh: "តាសាល" },
          { en: "Trapang Cho", kh: "ត្រពាំងជោ" },
        ],
      },
      {
        district: { en: "Bar Sdey", kh: "បរសេដ្ឋ" },
        communes: [
          { en: "Bar Sdey", kh: "បរសេដ្ឋ" },
          { en: "Kok", kh: "កក់" },
          { en: "Kat Phluk", kh: "កាត់ភ្លុក" },
          { en: "Nitean", kh: "និទាន" },
          { en: "Phakti", kh: "ភក្ដី" },
          { en: "Phari Mean Chey", kh: "ភារីមានជ័យ" },
          { en: "Phong", kh: "ផុង" },
          { en: "Poht Akkrang", kh: "ពោធិអង្ក្រង" },
          { en: "Poht Chamron", kh: "ពោធិ៍ចំរើន" },
          { en: "Poht Meral", kh: "ពោធិ៍ម្រាល" },
          { en: "Preah Khe", kh: "ព្រះខែ" },
          { en: "Svay Chachib", kh: "ស្វាយចចិប" },
          { en: "Svay Rompear", kh: "ស្វាយរំពារ" },
          { en: "Toul Ampil", kh: "ទួលអំពិល" },
          { en: "Toul Sala", kh: "ទួលសាលា" },
        ],
      },
      {
        district: { en: "Kong Pisei", kh: "គងពិសី" },
        communes: [
          { en: "Angkorpopal", kh: "អង្គពពេល" },
          { en: "Jorng Rok", kh: "ជង្រុក" },
          { en: "Maha Rassi", kh: "មហាឫស្សី" },
          { en: "Pech Muni", kh: "ពេជ្រមុនី" },
          { en: "Preah Niphan", kh: "ព្រះនិព្វាន" },
          { en: "Prey Nyati", kh: "ព្រៃញាតិ" },
          { en: "Prey Vihar", kh: "ព្រៃវិហារ" },
          { en: "Rok Akoh", kh: "រកាកោះ" },
          { en: "Stuk", kh: "ស្ដុក" },
          { en: "Snor Krapeu", kh: "ស្នំក្រពើ" },
          { en: "Srok", kh: "ស្រង់" },
          { en: "Tuk Lok", kh: "ទឹកល្អក់" },
          { en: "Veal", kh: "វាល" },
        ],
      },
      {
        district: { en: "Chbar Mon", kh: "ច្បារមន" },
        communes: [
          { en: "Chbar Mon", kh: "ច្បារមន" },
          { en: "Kandol Dum", kh: "កណ្ដោលដុំ" },
          { en: "Roka Thum", kh: "រកាធំ" },
          { en: "Soportep", kh: "សុព័រទេព" },
          { en: "Svay Kravan", kh: "ស្វាយក្រវ៉ាន់" },
        ],
      },
      {
        district: { en: "Odong Meach", kh: "ក្រុងឧដុង្គម៉ែជ័យ" },
        communes: [
          { en: "Ksemksand", kh: "ក្សេមក្សាន្ដ" },
          { en: "Preah Sre", kh: "ព្រះស្រែ" },
          { en: "Trach Tong", kh: "ត្រាចទង" },
          { en: "Veal Pong", kh: "វាលពង់" },
          { en: "Vang Chas", kh: "វាំងចាស់" },
        ],
      },
      {
        district: { en: "Phnom Sruoch", kh: "ភ្នំស្រួច" },
        communes: [
          { en: "Chambak", kh: "ចំបក់" },
          { en: "Jam Sangke", kh: "ជាំសង្កែ" },
          { en: "Dambok Rong", kh: "ដំបូករូង" },
          { en: "Kiri Vond", kh: "គិរីវន្ដ" },
          { en: "Krang Dey Vai", kh: "ក្រាំងដីវ៉ាយ" },
          { en: "Maha Sang", kh: "មហាសាំង" },
          { en: "Oru", kh: "អូរ" },
          { en: "Prey Kheang", kh: "ព្រៃក្មេង" },
          { en: "Prey Ramdul", kh: "ព្រៃរំដួល" },
          { en: "Tang Samrong", kh: "តាំងសំរោង" },
          { en: "Tang Sya", kh: "តាំងស្យា" },
          { en: "Treng Trayoung", kh: "ត្រែងត្រយឹង" },
        ],
      },
      {
        district: { en: "Samaki Mean Chey", kh: "សាមគ្គីមុនីជ័យ" },
        communes: [
          { en: "Chan Sen", kh: "ចាន់សែន" },
          { en: "Jeung Reas", kh: "ជើងរាស់" },
          { en: "Chompou Prek", kh: "ជំពូព្រឹក្ស" },
          { en: "Damnak Reng", kh: "ដំណាក់រាំង" },
          { en: "Krang Chek", kh: "ក្រាំងចេក" },
          { en: "Mean Chey", kh: "មានជ័យ" },
          { en: "Pang Lvea", kh: "ពាំងល្វា" },
          { en: "Phnom Toch", kh: "ភ្នំតូច" },
          { en: "Prey Krasang", kh: "ព្រៃក្រសាំង" },
          { en: "Yuth Samaki", kh: "យុទ្ធសាមគ្គី" },
        ],
      },
      {
        district: { en: "Samrong Tong", kh: "សំរោងទង" },
        communes: [
          { en: "Kaheng", kh: "កាហែង" },
          { en: "Khtum Krang", kh: "ខ្ទុំក្រាំង" },
          { en: "Krang Ampil", kh: "ក្រាំងអំពិល" },
          { en: "Pneay", kh: "ព្នាយ" },
          { en: "Rolang Chak", kh: "រលាំងចក" },
          { en: "Rolang Krael", kh: "រលាំងគ្រឹល" },
          { en: "Saeng Dei", kh: "សែងដី" },
          { en: "Sambor", kh: "សំបូរ" },
          { en: "Samrong Tong", kh: "សំរោងទង" },
          { en: "Skos", kh: "ស្គុះ" },
          { en: "Tang Kroch", kh: "តាំងក្រូច" },
          { en: "Thommatha Orl", kh: "ធម្មតាអរl" },
          { en: "Trapang Kong", kh: "ត្រពាំងគង" },
          { en: "Tompor Meas", kh: "ទំព័រមាស" },
          { en: "Vallisar", kh: "វល្លិសរ" },
        ],
      },
      {
        district: { en: "Thpong", kh: "ថ្ពង" },
        communes: [
          { en: "Amlang", kh: "អមលាំង" },
          { en: "Mano Rorm", kh: "មនោរម្យ" },
          { en: "Pram Bei Mum", kh: "ប្រាំបីមុម" },
          { en: "Rung Reung", kh: "រុងរឿង" },
          { en: "Top Mean", kh: "ទ័ពមាន" },
          { en: "Veal Pon", kh: "វាលពន់" },
          { en: "Ya Ang", kh: "យាអង្គ" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Kampong Thom",
      kh: "កំពង់ធំ",
    },
    districts: [
      {
        district: { en: "Baray", kh: "បារាយណ៍" },
        communes: [
          { en: "Andoung Poht", kh: "អណ្ដូងពោធិ៍" },
          { en: "Baksna", kh: "បាក់ស្នា" },
          { en: "Ballang", kh: "បល្ល័ង្គ" },
          { en: "Baray", kh: "បារាយណ៍" },
          { en: "Beung", kh: "បឹង" },
          { en: "Cheung Daeng", kh: "ចើងដើយ" },
          { en: "Chouk Khsach", kh: "ឈូកខ្សាច់" },
          { en: "Chong Dong", kh: "ចុងដូង" },
          { en: "Chranang", kh: "ច្រនាង" },
          { en: "Jrolong", kh: "ជ្រលង" },
          { en: "Kokithom", kh: "គគីធំ" },
          { en: "Krava", kh: "ក្រវ៉ា" },
          { en: "Pong", kh: "ពង្រ" },
          { en: "Suyoung", kh: "សូយោង" },
          { en: "Sralav", kh: "ស្រឡៅ" },
          { en: "Svay Phleung", kh: "ស្វាយភ្លើង" },
          { en: "Tnaot Jum", kh: "ត្នោតជុំ" },
          { en: "Triel", kh: "ទ្រៀល" },
        ],
      },
      {
        district: { en: "Kampong Svay", kh: "កំពង់ស្វាយ" },
        communes: [
          { en: "Chey", kh: "ជ័យ" },
          { en: "Domrei Slap", kh: "ដំរីស្លាប់" },
          { en: "Kampong Ko", kh: "កំពង់គោ" },
          { en: "Kampong Svay", kh: "កំពង់ស្វាយ" },
          { en: "Kdei Dong", kh: "ក្ដីដូង" },
          { en: "Nipech", kh: "នីពេជ" },
          { en: "Phat Sandai", kh: "ផាត់សណ្ដាយ" },
          { en: "Prey Kuy", kh: "ព្រៃគុយ" },
          { en: "San Ke", kh: "សាន់គ" },
          { en: "Tbang", kh: "ត្បែង" },
          { en: "Trapang Ue", kh: "ត្រពាំងឫស្សី" },
        ],
      },
      {
        district: { en: "Stueng Sen", kh: "ស្ទឹងសែន" },
        communes: [
          { en: "Acharya Lak", kh: "អាចារ្យលាក់" },
          { en: "Domrei Jan Khlav", kh: "ដំរីជាន់ខ្លា" },
          { en: "Kampong Krabao", kh: "កំពង់ក្របៅ" },
          { en: "Kampong Roteh", kh: "កំពង់រទេះ" },
          { en: "Kampong Thum", kh: "កំពង់ធំ" },
          { en: "Orkathara", kh: "អូរកន្ធរ" },
          { en: "Prey Ta Ho", kh: "ព្រៃតាហ៊ូ" },
          { en: "Srayov", kh: "ស្រយ៉ូវ" },
        ],
      },
      {
        district: { en: "Prasat Ballang", kh: "ប្រាសាទបល្ល័ង្គ" },
        communes: [
          { en: "Dong", kh: "ដូង" },
          { en: "Kraya", kh: "ក្រយា" },
          { en: "Phanh Yeum", kh: "ផាន់ញើម" },
          { en: "Sakream", kh: "សាគ្រាម" },
          { en: "Sala Visay", kh: "សាលាវិស័យ" },
          { en: "Samaki", kh: "សាមគ្គី" },
          { en: "Toul Krael", kh: "ទួលគ្រើល" },
        ],
      },
      {
        district: { en: "Prasat Sambor", kh: "ប្រាសាទសំបូរ" },
        communes: [
          { en: "Chouk", kh: "ឈូក" },
          { en: "Kol", kh: "គោល" },
          { en: "Sambor", kh: "សំបូរ" },
          { en: "Sraeng", kh: "ស្រែង" },
          { en: "Tang Krasao", kh: "តាំងក្រសៅ" },
        ],
      },
      {
        district: { en: "Sandan", kh: "សណ្ដាន់" },
        communes: [
          { en: "Cheu Teal", kh: "ឈើទាល" },
          { en: "Dong Kambit", kh: "ដងកាំបិត" },
          { en: "Klang", kh: "ក្លែង" },
          { en: "Mean Chey", kh: "មានជ័យ" },
          { en: "Mean Rith", kh: "មានរិទ្ធិ" },
          { en: "Nong", kh: "ងន" },
          { en: "Sandan", kh: "សណ្ដាន់" },
          { en: "Sochetra", kh: "សុចិត្រ" },
          { en: "Tomring", kh: "ទំរីង" },
        ],
      },
      {
        district: { en: "Santok", kh: "សន្ទុក" },
        communes: [
          { en: "Beung Lvea", kh: "បឹងល្វា" },
          { en: "Chrop", kh: "ជ្រាប់" },
          { en: "Kakoh", kh: "កកោះ" },
          { en: "Kampong Thma", kh: "កំពង់ថ្ម" },
          { en: "Kraya", kh: "ក្រយា" },
          { en: "Pneav", kh: "ព្នៅ" },
          { en: "Prasat", kh: "ប្រាសាទ" },
          { en: "Tang Krasang", kh: "តាំងក្រសាំង" },
          { en: "Tboung Krapeu", kh: "ត្បូងក្រពើ" },
          { en: "Tipou", kh: "ទីពោ" },
        ],
      },
      {
        district: { en: "Stoung", kh: "ស្ទោង" },
        communes: [
          { en: "Banteay Stoung", kh: "បន្ទាយស្ទោង" },
          { en: "Cham Nakrom", kh: "ចំណាក្រោម" },
          { en: "Cham Naklear", kh: "ចំណាលើ" },
          { en: "Kampong Chin Jeung", kh: "កំពង់ចិនជើង" },
          { en: "Kampong Chin Tboung", kh: "កំពង់ចិនត្បូង" },
          { en: "Msa Krang", kh: "ម្សាក្រង" },
          { en: "Peam Bang", kh: "ពាមបាង" },
          { en: "Popok", kh: "ពពក" },
          { en: "Bralay", kh: "ប្រឡាយ" },
          { en: "Preah Domrei", kh: "ព្រះដំរី" },
          { en: "Rung Reung", kh: "រុងរឿង" },
          { en: "Sam Proach", kh: "សំព្រោជ" },
          { en: "Trea", kh: "ទ្រា" },
        ],
      },
    ],
  },
  {
    province: {
      en: "Kampot",
      kh: "កំពត",
    },
    districts: [
      {
        district: { en: "Angkor Chey", kh: "អង្គរជ័យ" },
        communes: [
          { en: "Angkor Phnom Toch", kh: "អង្គភ្នំតូច" },
          { en: "Angkor Chey", kh: "អង្គរជ័យ" },
          { en: "Champey", kh: "ចំប៉ី" },
          { en: "Daem Dong", kh: "ដើមដូង" },
          { en: "Dambok Kpuos", kh: "ដំបូកខ្ពស់" },
          { en: "Dane Koum", kh: "ដានគោម" },
          { en: "Mroam", kh: "ម្រោម" },
          { en: "Phnom Kong", kh: "ភ្នំកុង" },
          { en: "Prophnom", kh: "ប្រភ្នំ" },
          { en: "Samlenh", kh: "សំឡាញ" },
          { en: "Tani", kh: "តានី" },
        ],
      },
      {
        district: { en: "Banteay Meanchey", kh: "បន្ទាយមាស" },
        communes: [
          { en: "Banteay Meanchey East", kh: "បន្ទាយមាសខាងកើត" },
          { en: "Banteay Meanchey West", kh: "បន្ទាយមាសខាងលិច" },
          { en: "Prey Tontle", kh: "ព្រៃទន្លេ" },
          { en: "Samrong Krom", kh: "សំរោងក្រោម" },
          { en: "Samrong Leu", kh: "សំរោងលើ" },
          { en: "Staej Kong North", kh: "ស្ដេចគង់ខាងជើង" },
          { en: "Staej Kong West", kh: "ស្ដេចគង់ខាងលិច" },
          { en: "Staej Kong South", kh: "ស្ដេចគង់ខាងត្បូង" },
          { en: "Tnaot Chong Sralok", kh: "ត្នោតចុងស្រង់" },
          { en: "Trapeang Sala East", kh: "ត្រពាំងសាលាខាងកើត" },
          { en: "Trapeang Sala West", kh: "ត្រពាំងសាលាខាងលិច" },
          { en: "Tuk Meas East", kh: "ទូកមាសខាងកើត" },
          { en: "Tuk Meas West", kh: "ទូកមាសខាងលិច" },
          { en: "Vatt Angkor North", kh: "វត្ដអង្គខាងជើង" },
          { en: "Vatt Angkor South", kh: "វត្ដអង្គខាងត្បូង" },
        ],
      },
      {
        district: { en: "Chhuk", kh: "ឈូក" },
        communes: [
          { en: "Baneav", kh: "បានៀវ" },
          { en: "Boeng Nimul", kh: "បឹងនិមល" },
          { en: "Chhuk", kh: "ឈូក" },
          { en: "Doun Yoy", kh: "ដូនយ៉យ" },
          { en: "Krang Sbov", kh: "ក្រាំងស្បូវ" },
          { en: "Krang Snay", kh: "ក្រាំងស្នាយ" },
          { en: "Lbek", kh: "ល្បើក" },
          { en: "Meanjei", kh: "មានជ័យ" },
          { en: "Narayan", kh: "នារាយណ៍" },
          { en: "Satt Phong", kh: "សត្វពង" },
          { en: "Takeyn", kh: "តាកែន" },
          { en: "Tremaing", kh: "ត្រមែង" },
          { en: "Trapeang Bei", kh: "ត្រពាំងបី" },
          { en: "Trapeang Phlang Ra", kh: "ត្រពាំងភ្លាំងរ" },
        ],
      },
      {
        district: { en: "Chumkiri", kh: "ជុំគិរី" },
        communes: [
          { en: "Chres", kh: "ច្រេស" },
          { en: "Chom Povndt", kh: "ជំពូវន្ដ" },
          { en: "Snay Anchet", kh: "ស្នាយអញ្ជិត" },
          { en: "Srae Cheang", kh: "ស្រែចែង" },
          { en: "Srae Knong", kh: "ស្រែកក្នុង" },
          { en: "Srae Samrong", kh: "ស្រែសំរោង" },
          { en: "Trapeang Reang", kh: "ត្រពាំងរាំង" },
        ],
      },
      {
        district: { en: "Dang Tong", kh: "ដងទង់" },
        communes: [
          { en: "Angkor Ramas", kh: "អង្គ រមាស" },
          { en: "Damnack Sokram", kh: "ដំណាក់សុក្រំ" },
          { en: "Dang Tong", kh: "ដងទង់" },
          { en: "Khjeay North", kh: "ខ្ជាយខាងជើង" },
          { en: "Khjeay South", kh: "ខ្ជាយខាងត្បូង" },
          { en: "Leang", kh: "ល្អាង" },
          { en: "Mean Rith", kh: "មានរិទ្ធិ" },
          { en: "Srae Cheang North", kh: "ស្រែជាខាងជើង" },
          { en: "Srae Cheang South", kh: "ស្រែជាខាងត្បូង" },
          { en: "Ttung", kh: "ទទុង" },
        ],
      },
      {
        district: { en: "Kampong Trach", kh: "កំពង់ត្រាច" },
        communes: [
          { en: "Boeng Sala North", kh: "បឹងសាលាខាងជើង" },
          { en: "Boeng Sala South", kh: "បឹងសាលាខាងត្បូង" },
          { en: "Damnack Kantout North", kh: "ដំណាក់កន្ទួតខាងជើង" },
          { en: "Damnack Kantout South", kh: "ដំណាក់កន្ទួតខាងត្បូង" },
          { en: "Kampong Trach East", kh: "កំពង់ត្រាចខាងកើត" },
          { en: "Kampong Trach West", kh: "កំពង់ត្រាចខាងលិច" },
          { en: "Kanthor North", kh: "គន្ធរខាងជើង" },
          { en: "Kanthor East", kh: "គន្ធរខាងកើត" },
          { en: "Kanthor West", kh: "គន្ធរខាងលិច" },
          { en: "Prek Kres", kh: "ព្រែកក្រឹស" },
          { en: "Ruessey Srok East", kh: "ឫស្សីស្រុកខាងកើត" },
          { en: "Ruessey Srok West", kh: "ឫស្សីស្រុកខាងលិច" },
          { en: "Svay Tong North", kh: "ស្វាយទងខាងជើង" },
          { en: "Svay Tong South", kh: "ស្វាយទងខាងត្បូង" },
        ],
      },
      {
        district: { en: "Kampot", kh: "កំពត" },
        communes: [
          { en: "Andong Khmer", kh: "អណ្ដូងខ្មែរ" },
          { en: "Kampong Bay", kh: "កំពង់បាយ" },
          { en: "Kampong Kandal", kh: "កំពង់កណ្ដាល" },
          { en: "Krang Ampil", kh: "ក្រាំងអំពិល" },
          { en: "Traloy Koh", kh: "ត្រើយកោះ" },
        ],
      },
      {
        district: { en: "Tuk Chhou", kh: "ទឹកឈូ" },
        communes: [
          { en: "Boeng Tuk", kh: "បឹងទូក" },
          { en: "Chum Kril", kh: "ជុំគ្រៀល" },
          { en: "Kampong Krang", kh: "កំពង់ក្រែង" },
          { en: "Kampong Samrong", kh: "កំពង់សំរោង" },
          { en: "Kandal", kh: "កណ្ដាល" },
          { en: "Koh Toch", kh: "កោះតូច" },
          { en: "Koun Satv", kh: "កូនសត្វ" },
          { en: "Mak Brang", kh: "ម៉ាក់ប្រាង្គ" },
          { en: "Prek Tnaot", kh: "ព្រែកត្នោត" },
          { en: "Prey Khmum", kh: "ព្រៃឃ្មុំ" },
          { en: "Prey Thang", kh: "ព្រៃថ្នង" },
          { en: "Stung Kaev", kh: "ស្ទឹងកែវ" },
          { en: "Thmei", kh: "ថ្មី" },
          { en: "Trapeang Pring", kh: "ត្រពាំងព្រីង" },
          { en: "Trapeang Sangkae", kh: "ត្រពាំងសង្កែ" },
          { en: "Trapeang Thom", kh: "ត្រពាំងធំ" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Kep",
      kh: "កែប",
    },
    districts: [
      {
        district: { en: "Damnak Chhkae", kh: "ដំណាក់ចង្អើរ" },
        communes: [
          { en: "Angkol", kh: "អង្កោល" },
          { en: "Or Krasar", kh: "អូរក្រសារ" },
          { en: "Pong Teuk", kh: "ពងទឹក" },
        ],
      },
      {
        district: { en: "Kep", kh: "កែប" },
        communes: [
          { en: "Kep", kh: "កែប" },
          { en: "Prey Thom", kh: "ព្រៃធំ" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Koh Kong",
      kh: "កោះកុង",
    },
    districts: [
      {
        district: { en: "Battambang", kh: "បុទុមសាគរ" },
        communes: [
          { en: "Andong Teuk", kh: "អណ្ដូងទឹក" },
          { en: "Kandol", kh: "កណ្ដោល" },
          { en: "Tanuon", kh: "តានួន" },
          { en: "Thma Se", kh: "ថ្មស" },
        ],
      },
      {
        district: { en: "Kiri Sakor", kh: "គិរីសាគរ" },
        communes: [
          { en: "Koh Sdei", kh: "កោះស្ដេច" },
          { en: "Phni Meas", kh: "ភ្ញីមាស" },
          { en: "Prek Khsach", kh: "ព្រែកខ្សាច់" },
        ],
      },
      {
        district: { en: "Koh Kong", kh: "កោះកុង" },
        communes: [
          { en: "Chroy Pros", kh: "ជ្រោយប្រស់" },
          { en: "Koh Kapi", kh: "កោះកាពិ" },
          { en: "Tatai Kraom", kh: "តាតៃក្រោម" },
          { en: "Tropang Rung", kh: "ត្រពាំងរូង" },
        ],
      },
      {
        district: { en: "Kampong Thom", kh: "ខេមរភូមិន្ទ" },
        communes: [
          { en: "Dong Tong", kh: "ដងទង់" },
          { en: "Smach Mean Chey", kh: "ស្មាច់មានជ័យ" },
          { en: "Steung Veng", kh: "ស្ទឹងវែង" },
        ],
      },
      {
        district: { en: "Mondulkiri", kh: "មណ្ឌលសីមា" },
        communes: [
          { en: "Pak Khlong", kh: "ប៉ាក់ខ្លង" },
          { en: "Peam Krasoab", kh: "ពាមក្រសោប" },
          { en: "Toul Kokir", kh: "ទួលគគីរ" },
        ],
      },
      {
        district: { en: "Srae Ambel", kh: "ស្រែ អំបិល" },
        communes: [
          { en: "Bung Preav", kh: "បឹងព្រាវ" },
          { en: "Ji Kh Kreom", kh: "ជី ខ ក្រោម" },
          { en: "Ji Kh Ler", kh: "ជី ខ លើ" },
          { en: "Chroy Svay", kh: "ជ្រោយស្វាយ" },
          { en: "Dong Paeng", kh: "ដងពែង" },
          { en: "Srae Ambel", kh: "ស្រែអំបិល" },
        ],
      },
      {
        district: { en: "Thma Bang", kh: "ថ្មបាំង" },
        communes: [
          { en: "Ji Phat", kh: "ជីផាត" },
          { en: "Jom Nap", kh: "ជំនាប់" },
          { en: "Prelay", kh: "ប្រឡាយ" },
          { en: "Ruessei Jrom", kh: "ឫស្សីជ្រុំ" },
          { en: "Ta Tai Ler", kh: "តាទៃលើ" },
          { en: "Thma Doun Pao", kh: "ថ្មដូនពៅ" },
        ],
      },
    ],
  },
  {
    province: {
      en: "Krech",
      kh: "ក្រចេះ",
    },
    districts: [
      {
        district: { en: "Chhlong", kh: "ឆ្លូង" },
        communes: [
          { en: "Chhlong", kh: "ឆ្លូង" },
          { en: "Dumrey Phong", kh: "ដំរីផុង" },
          { en: "Han Chey", kh: "ហាន់ជ័យ" },
          { en: "Kampong Dumrey", kh: "កំពង់ដំរី" },
          { en: "Kang Chea", kh: "កញ្ជរ" },
          { en: "Khsach Andet", kh: "ខ្សាច់អណ្ដែត" },
          { en: "Pongr", kh: "ពង្រ" },
          { en: "Prek Samon", kh: "ព្រែកសាម៉ាន់" },
        ],
      },
      {
        district: { en: "Chitro Buri", kh: "ចិត្របុរី" },
        communes: [
          { en: "Bos Lave", kh: "បុសលាវ" },
          { en: "Chong Krang", kh: "ចង្ក្រង់" },
          { en: "Dar", kh: "ដារ" },
          { en: "Kantout", kh: "កន្ទួត" },
          { en: "Koh Chrang", kh: "កោះច្រែង" },
          { en: "Kolab", kh: "គោលាប់" },
          { en: "Sambok", kh: "សំបុក" },
          { en: "Thma Andeak", kh: "ថ្មអណ្ដើក" },
          { en: "Thma Kre", kh: "ថ្មគ្រែ" },
          { en: "Thmei", kh: "ថ្មី" },
        ],
      },
      {
        district: { en: "Kraché", kh: "ក្រចេះ" },
        communes: [
          { en: "Koh Trong", kh: "កោះទ្រង់" },
          { en: "Kraché", kh: "ក្រចេះ" },
          { en: "Krakor", kh: "ក្រគរ" },
          { en: "Orussey", kh: "អូរឫស្សី" },
          { en: "Rokakandal", kh: "រកាកណ្ដាល" },
        ],
      },
      {
        district: { en: "Ou Kreang Sen Chey", kh: "អូរគ្រៀងសែនជ័យ" },
        communes: [
          { en: "Kbal Dumrey", kh: "ក្បាលដំរី" },
          { en: "Oukandear Sen Chey", kh: "អូរកណ្តៀរសែនជ័យ" },
          { en: "Oukreang", kh: "អូរគ្រៀង" },
          { en: "Roulous Mean Chey", kh: "រលួសមានជ័យ" },
          { en: "Srae Che", kh: "ស្រែជិះ" },
        ],
      },
      {
        district: { en: "Prek Brasov", kh: "ព្រែកប្រសព្វ" },
        communes: [
          { en: "Chambok", kh: "ចំបក់" },
          { en: "Chraoy Banteay", kh: "ជ្រោយបន្ទាយ" },
          { en: "Kampong Kor", kh: "កំពង់គរ" },
          { en: "Koh Ta Suy", kh: "កោះតាស៊ុយ" },
          { en: "Prek Brasov", kh: "ព្រែកប្រសព្វ" },
          { en: "Ras Sy Kaev", kh: "ឫស្សីកែវ" },
          { en: "Sop", kh: "សោប" },
          { en: "Tamau", kh: "តាម៉ៅ" },
        ],
      },
      {
        district: { en: "Sambour", kh: "សំបូរ" },
        communes: [
          { en: "Bung Char", kh: "បឹងចារ" },
          { en: "Kampong Cham", kh: "កំពង់ចាម" },
          { en: "Koh Khner", kh: "កោះខ្ញែរ" },
          { en: "Sambour", kh: "សំបូរ" },
          { en: "Sndan", kh: "សណ្ដាន់" },
          { en: "Vadhana", kh: "វឌ្ឍនៈ" },
        ],
      },
      {
        district: { en: "Snoul", kh: "ស្នួល" },
        communes: [
          { en: "Khsem", kh: "ឃ្សឹម" },
          { en: "Pir Thnu", kh: "ពីរធ្នូ" },
          { en: "Snoul", kh: "ស្នួល" },
          { en: "Srae Char", kh: "ស្រែចារ" },
          { en: "Svay Chhreh", kh: "ស្វាយជ្រះ" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Mondol Kiri",
      kh: "មណ្ឌលគីរី",
    },
    districts: [
      {
        district: { en: "Kaev Sima", kh: "កែវសីមា" },
        communes: [
          { en: "Chong Plas", kh: "ចុងផ្លាស់" },
          { en: "Memong", kh: "មេម៉ង់" },
          { en: "Srae Chouk", kh: "ស្រែឈូក" },
          { en: "Srae Khtum", kh: "ស្រែខ្ទុម" },
          { en: "Srae Preah", kh: "ស្រែព្រះ" },
        ],
      },
      {
        district: { en: "Koh Nhek", kh: "កោះញែក" },
        communes: [
          { en: "Nang Khillic", kh: "ណងឃីលិក" },
          { en: "A Boun Leu", kh: "អ បួនលើ" },
          { en: "Roy", kh: "រយ៉" },
          { en: "Sok Sand", kh: "សុខសាន្ដ" },
          { en: "Srae Huy", kh: "ស្រែហ៊ុយ" },
          { en: "Srae Sangkum", kh: "ស្រែសង្គម" },
        ],
      },
      {
        district: { en: "Sen Monorom", kh: "សែនមនោរម្យ" },
        communes: [
          { en: "Monorom", kh: "មនោរម្យ" },
          { en: "Romnea", kh: "រមនា" },
          { en: "Sok Dom", kh: "សុខដុម" },
          { en: "Spian Mean Chey", kh: "ស្ពានមានជ័យ" },
        ],
      },
      {
        district: { en: "Orang Reng", kh: "អូររាំង" },
        communes: [
          { en: "Dak Dam", kh: "ដាក់ដាំ" },
          { en: "Sen Monorom", kh: "សែនមនោរម្យ" },
        ],
      },
      {
        district: { en: "Pechra Da", kh: "ពេជ្រាដា" },
        communes: [
          { en: "Puchrei", kh: "ពូជ្រៃ" },
          { en: "Bousra", kh: "ប៊ូស្រា" },
          { en: "Krang Teh", kh: "ក្រង់តេះ" },
          { en: "Srae Ampum", kh: "ស្រែអំពូម" },
        ],
      },
    ],
  },

  {
    province: {
      en: "Uttmean Chey",
      kh: "ឧត្តមានជ័យ",
    },
    districts: [
      {
        district: { en: "Anlong Veng", kh: "អន្លង់វែង" },
        communes: [
          { en: "Lamtong", kh: "លំទង" },
          { en: "Thlat", kh: "ថ្លាត" },
          { en: "Trapang Prey", kh: "ត្រពាំងប្រីយ៍" },
          { en: "Trapang Tav", kh: "ត្រពាំងតាវ" },
        ],
      },
      {
        district: { en: "Banteay Ampil", kh: "បន្ទាយអំពិល" },
        communes: [
          { en: "Ampil", kh: "អំពិល" },
          { en: "Beng", kh: "បេង" },
          { en: "Kok Kphos", kh: "គោកខ្ពស់" },
          { en: "Kok Mon", kh: "គោកមន" },
        ],
      },
      {
        district: { en: "Chong Kal", kh: "ចុងកាល់" },
        communes: [
          { en: "Cheung Tean", kh: "ជើងទៀន" },
          { en: "Chong Kal", kh: "ចុងកាល់" },
          { en: "Krasang", kh: "ក្រសាំង" },
          { en: "Pongr", kh: "ពង្រ" },
        ],
      },
      {
        district: { en: "Samraong", kh: "សំរោង" },
        communes: [
          { en: "Bansay Reak", kh: "បន្សាយរាក់" },
          { en: "Bussov", kh: "បុស្បូវ" },
          { en: "Koun Kriel", kh: "កូនក្រៀល" },
          { en: "Oursmach", kh: "អូរស្មាច់" },
          { en: "Samraong", kh: "សំរោង" },
        ],
      },
      {
        district: { en: "Trapang Banteay", kh: "ត្រពាំងប្រាសាទ" },
        communes: [
          { en: "Bak Anlong", kh: "បាក់អន្លូង" },
          { en: "Oursvay", kh: "អូរស្វាយ" },
          { en: "Phav", kh: "ផ្អាវ" },
          { en: "Preah Braiy", kh: "ព្រះប្រឡាយ" },
          { en: "Trapang Banteay", kh: "ត្រពាំងប្រាសាទ" },
          { en: "Tum Nop Dach", kh: "ទំនប់ដាច់" },
        ],
      },
    ],
  },
  {
    province: {
      en: "Bailin",
      kh: "បៃលិន",
    },
    districts: [
      {
        district: { en: "Bailin", kh: "ប៉ៃលិន" },
        communes: [
          { en: "Baray Kha", kh: "បរយ៉ាខា" },
          { en: "O Tavao", kh: "អូរតាវ៉ៅ" },
          { en: "Bailin", kh: "ប៉ៃលិន" },
          { en: "Tuol Lvea", kh: "ទួលល្វា" },
        ],
      },
      {
        district: { en: "Sala Krau", kh: "សាលាក្រៅ" },
        communes: [
          { en: "O Andoung", kh: "អូរអណ្ដូង" },
          { en: "Sala Krau", kh: "សាលាក្រៅ" },
          { en: "Steung Kach", kh: "ស្ទឹងកាច់" },
          { en: "Steung Trang", kh: "ស្ទឹងត្រង់" },
        ],
      },
    ],
  },
  {
    province: {
      en: "Preah Vihear",
      kh: "ព្រះវិហារ",
    },
    districts: [
      {
        district: { en: "Cheysang", kh: "ជ័យសែន" },
        communes: [
          { en: "Chrach", kh: "ច្រាច់" },
          { en: "Kyang", kh: "ខ្យង" },
          { en: "Putra", kh: "ពុទ្រា" },
          { en: "Saang", kh: "ស្អាង" },
          { en: "Tasu", kh: "តស៊ូ" },
          { en: "Thma", kh: "ធ្មា" },
        ],
      },
      {
        district: { en: "Cheb", kh: "ឆែប" },
        communes: [
          { en: "Cheb 1", kh: "ឆែបមួយ" },
          { en: "Cheb 2", kh: "ឆែបពីរ" },
          { en: "Kampong Sralau 1", kh: "កំពង់ស្រឡៅមួយ" },
          { en: "Kampong Sralau 2", kh: "កំពង់ស្រឡៅពីរ" },
          { en: "Mlu Prey 1", kh: "ម្លូព្រៃមួយ" },
          { en: "Mlu Prey 2", kh: "ម្លូព្រៃពីរ" },
          { en: "Sangke 1", kh: "សង្កែមួយ" },
          { en: "Sangke 2", kh: "សង្កែពីរ" },
        ],
      },
      {
        district: { en: "Jamk Sant", kh: "ជាំក្សាន្ដ" },
        communes: [
          { en: "Jamk Sant", kh: "ជាំក្សាន្ដ" },
          { en: "Kantout", kh: "កន្ទួត" },
          { en: "Preing Thum", kh: "ព្រីងធំ" },
          { en: "Ramdah Srae", kh: "រំដោះស្រែ" },
          { en: "Tuk Kraham", kh: "ទឹកក្រហម" },
          { en: "Yang", kh: "យាង" },
        ],
      },
      {
        district: { en: "Krung Preah Vihear", kh: "ក្រុងព្រះវិហារ" },
        communes: [
          { en: "Kampong Pranak", kh: "កំពង់ប្រណាក" },
          { en: "Palhal", kh: "ប៉ាលហាល" },
        ],
      },
      {
        district: { en: "Kulen", kh: "គូលែន" },
        communes: [
          { en: "Kulen Cheung", kh: "គូលែនជើង" },
          { en: "Kulen Tboung", kh: "គូលែនត្បូង" },
          { en: "Phnom Penh", kh: "ភ្នំពេញ" },
          { en: "Phnom Tbaeng 2", kh: "ភ្នំត្បែងពីរ" },
          { en: "Srayong", kh: "ស្រយង់" },
          { en: "Thmei", kh: "ថ្មី" },
        ],
      },
      {
        district: { en: "Rvieng", kh: "រវៀង" },
        communes: [
          { en: "Roksa", kh: "រក្សា" },
          { en: "Resmei", kh: "រស្មី" },
          { en: "Riep Ror", kh: "រៀបរយ" },
          { en: "Rik Reay", kh: "រីករាយ" },
          { en: "Rabeap", kh: "របៀប" },
          { en: "Rahas", kh: "រហ័ស" },
          { en: "Ramani", kh: "រមណីយ" },
          { en: "Ramtum", kh: "រមទម" },
          { en: "Ratanak", kh: "រតនៈ" },
          { en: "Ramday", kh: "រំដោះ" },
          { en: "Rungreung", kh: "រុងរឿង" },
          { en: "Rusran", kh: "រួសរាន់" },
        ],
      },
      {
        district: { en: "Sangkum Thmei", kh: "សង្គមថ្មី" },
        communes: [
          { en: "Chamron", kh: "ចំរើន" },
          { en: "Phnom Tbaeng 1", kh: "ភ្នំត្បែងមួយ" },
          { en: "Reang", kh: "រអាង" },
          { en: "Ranasir", kh: "រណសិរ្ស" },
          { en: "Stav", kh: "ស្ដៅ" },
        ],
      },
      {
        district: { en: "Tbaeng Mean Chey", kh: "ត្បែងមានជ័យ" },
        communes: [
          { en: "Chean Mukh", kh: "ឈានមុខ" },
          { en: "Puth", kh: "ពោធិ៍" },
          { en: "Bramero", kh: "ប្រមេរុ" },
          { en: "Preah Khleang", kh: "ព្រះឃ្លាំង" },
        ],
      },
    ],
  },
  {
    province: {
      en: "Prey Veng",
      kh: " ព្រៃវែង",
    },
    districts: [
      {
        district: { en: "Baphnum", kh: "បាភ្នំ" },
        communes: [
          { en: "Beung Preah", kh: "បឹងព្រះ" },
          { en: "Cheung Phnum", kh: "ជើងភ្នំ" },
          { en: "Cheur Kach", kh: "ឈើកាច់" },
          { en: "Roksa Chey", kh: "រក្សជ័យ" },
          { en: "Rong Domrei", kh: "រោងដំរី" },
          { en: "Sdao Kaong", kh: "ស្ដៅកោង" },
          { en: "Speu K", kh: "ស្ពឺ ក" },
          { en: "Speu Kh", kh: "ស្ពឺ ខ" },
          { en: "Thay", kh: "ធាយ" },
        ],
      },
      {
        district: { en: "Kampong Chhay", kh: "កំចាយមារ" },
        communes: [
          { en: "Cheach", kh: "ជាច" },
          { en: "Doun Keng", kh: "ដូនកឹង" },
          { en: "Krapav", kh: "ក្របៅ" },
          { en: "Kruong", kh: "ក្រញូង" },
          { en: "Seang Khvang", kh: "ស៊ាងឃ្វាង" },
          { en: "Smaong Khang Cheung", kh: "ស្មោងខាងជើង" },
          { en: "Smaong Khang Tboung", kh: "ស្មោងខាងត្បូង" },
          { en: "Trabeak", kh: "ត្របែក" },
        ],
      },
      {
        district: { en: "Puth Reang", kh: "ពោធិ៍រៀង" },
        communes: [
          { en: "Puth Reang", kh: "ពោធិ៍រៀង" },
          { en: "Prek Anthe", kh: "ព្រែកអន្ទះ" },
          { en: "Prek Chray", kh: "ព្រែកជ្រៃ" },
          { en: "Prey Kanhlong", kh: "ព្រៃកន្លោង" },
          { en: "Tako", kh: "តាកោ" },
        ],
      },
      {
        district: { en: "Kampong Trabeak", kh: "កំពង់ត្របែក" },
        communes: [
          { en: "Ansaong", kh: "អន្សោង" },
          { en: "Cham", kh: "ចាម" },
          { en: "Cheang Dak", kh: "ជាងដែក" },
          { en: "Chray", kh: "ជ្រៃ" },
          { en: "Kampong Trabeak", kh: "កំពង់ត្របែក" },
          { en: "Kansom Ak", kh: "កន្សោមអក" },
          { en: "Ko Kheak", kh: "គោខ្ចក" },
          { en: "Piam Mantrea", kh: "ពាមមន្ទារ" },
          { en: "Prasat", kh: "ប្រាសាទ" },
          { en: "Protheat", kh: "ប្រធាតុ" },
          { en: "Prey Chher", kh: "ព្រៃឈរ" },
          { en: "Prey Pon", kh: "ព្រៃពោន" },
          { en: "Thkov", kh: "ថ្កូវ" },
        ],
      },
      {
        district: { en: "Kan Chreach", kh: "កញ្ជ្រៀច" },
        communes: [
          { en: "Chong Ampil", kh: "ចុងអំពិល" },
          { en: "Kan Chreach", kh: "កញ្ជ្រៀច" },
          { en: "Kdueng Rey", kh: "ក្ដឿងរាយ" },
          { en: "Koak Kong Koat", kh: "គោកគង់កើត" },
          { en: "Koak Kong Lich", kh: "គោកគង់លិច" },
          { en: "Preal", kh: "ព្រាល" },
          { en: "Thmor Poun", kh: "ថ្មពូន" },
          { en: "Tnot", kh: "ត្នោត" },
        ],
      },
      {
        district: { en: "Prey Veng", kh: "ព្រៃវែង" },
        communes: [
          { en: "Baray", kh: "បារាយណ៍" },
          { en: "Cheung Tek", kh: "ជើងទឹក" },
          { en: "Kampong Leav", kh: "កំពង់លាវ" },
        ],
      },
      {
        district: { en: "Mesang", kh: "មេសាង" },
        communes: [
          { en: "Angkor Sas", kh: "អង្គរសរ" },
          { en: "Chey Phok", kh: "ជីផុច" },
          { en: "Chres", kh: "ច្រេស" },
          { en: "Prey Khnes", kh: "ព្រៃឃ្នេស" },
          { en: "Prey Romdeng", kh: "ព្រៃរំដេង" },
          { en: "Prey Totung", kh: "ព្រៃទទឹង" },
          { en: "Svay Jrom", kh: "ស្វាយជ្រុំ" },
          { en: "Trapeang Srae", kh: "ត្រពាំងស្រែ" },
        ],
      },
      {
        district: { en: "Parang", kh: "ពារាំង" },
        communes: [
          { en: "Kampong Popil", kh: "កំពង់ពពិល" },
          { en: "Kampong Prang", kh: "កំពង់ប្រាំង" },
          { en: "Kampong Russei", kh: "កំពង់ឫស្សី" },
          { en: "Kanh", kh: "កញ្ចំ" },
          { en: "Mesarabachan", kh: "មេសរប្រចាន់" },
          { en: "Prek Tasa", kh: "ព្រែកតាសរ" },
          { en: "Prey Pnov", kh: "ព្រៃព្នៅ" },
          { en: "Prey Snea", kh: "ព្រៃស្នៀត" },
          { en: "Prey Sralit", kh: "ព្រៃស្រឡិត" },
          { en: "Reap", kh: "រាប" },
          { en: "Raka", kh: "រកា" },
        ],
      },
      {
        district: { en: "Peam Chear", kh: "ពាមជរ" },
        communes: [
          { en: "Angkor Ang", kh: "អង្គរអង្គ" },
          { en: "Kampong Prasat", kh: "កំពង់ប្រាសាទ" },
          { en: "Koh Chek", kh: "កោះចេក" },
          { en: "Koh Roka", kh: "កោះរកា" },
          { en: "Koh Sampov", kh: "កោះសំពៅ" },
          { en: "Krang Taiyang", kh: "ក្រាំងតាយ៉ង" },
          { en: "Prek Krabav", kh: "ព្រែកក្របៅ" },
          { en: "Prek Sambour", kh: "ព្រែកសំបួរ" },
          { en: "Russei Srok", kh: "ឫស្សីស្រុក" },
          { en: "Svay Phluah", kh: "ស្វាយភ្លោះ" },
        ],
      },
      {
        district: { en: "Peam Rok", kh: "ពាមរក៍" },
        communes: [
          { en: "Baboang", kh: "បាបោង" },
          { en: "Banleach Prasat", kh: "បន្លិចប្រាសាទ" },
          { en: "Neak Loeung", kh: "អ្នកលឿង" },
          { en: "Peam Chey", kh: "ពាមមានជ័យ" },
          { en: "Peam Rok", kh: "ពាមរក៍" },
          { en: "Prek Khsaay K", kh: "ព្រែកខ្សាយ ក" },
          { en: "Prek Khsaay Kh", kh: "ព្រែកខ្សាយ ខ" },
          { en: "Prey Kandyang", kh: "ព្រៃកណ្ដៀង" },
        ],
      },
      {
        district: { en: "Preah Sdech", kh: "ព្រះស្ដេច" },
        communes: [
          { en: "Angkor Reach", kh: "អង្គររាជ្យ" },
          { en: "Banteay Chakri", kh: "បន្ទាយចក្រី" },
          { en: "Beung Daol", kh: "បឹងដោល" },
          { en: "Chey Kompok", kh: "ជៃកំពក" },
          { en: "Kampong Seng", kh: "កំពង់សឹង" },
          { en: "Krang Svay", kh: "ក្រាំងស្វាយ" },
          { en: "Lvea", kh: "ល្វា" },
          { en: "Preah Sdech", kh: "ព្រះស្ដេច" },
          { en: "Rathor", kh: "រាធរ" },
          { en: "Romchek", kh: "រំចេក" },
          { en: "Senaraj Utom", kh: "សេនារាជឧត្ដម" },
        ],
      },
      {
        district: { en: "Sithar Kondal", kh: "ស៊ីធរកណ្ដាល" },
        communes: [
          { en: "Ampil Khrao", kh: "អំពិលក្រៅ" },
          { en: "Chray Khmum", kh: "ជ្រៃឃ្មុំ" },
          { en: "Lve", kh: "ល្វេ" },
          { en: "Pnov Ti 1", kh: "ព្នៅទី ១" },
          { en: "Pnov Ti 2", kh: "ព្នៅទី ២" },
          { en: "Puth Ti", kh: "ពោធិ៍ទី" },
          { en: "Prek Chongkran", kh: "ព្រែកចង្ក្រាន" },
          { en: "Prey Daum Thnung", kh: "ព្រៃដើមថ្នឹង" },
          { en: "Prey Tueng", kh: "ព្រៃទឹង" },
          { en: "Russei Sanh", kh: "ឫស្សីសាញ់" },
          { en: "Rumlach", kh: "រំលេច" },
        ],
      },
      {
        district: { en: "Svay Antor", kh: "ស្វាយអន្ទរ" },
        communes: [
          { en: "Angkor Tret", kh: "អង្គរទ្រេត" },
          { en: "Chea Khlang", kh: "ជាខ្លាង" },
          { en: "Chray", kh: "ជ្រៃ" },
          { en: "Domrei Phoun", kh: "ដំរីពួន" },
          { en: "Mebon", kh: "មេបុណ្យ" },
          { en: "Pang Rong", kh: "ពានរោង" },
          { en: "Popus", kh: "ពពឺស" },
          { en: "Prey Khla", kh: "ព្រៃខ្លា" },
          { en: "Samrong", kh: "សំរោង" },
          { en: "Svay Antor", kh: "ស្វាយអន្ទរ" },
          { en: "Tuk Thla", kh: "ទឹកថ្លា" },
        ],
      },
    ],
  },
  {
    province: {
      en: "Puth Sat",
      kh: "ពោធិ៍សាត់",
    },
    districts: [
      {
        district: { en: "Bakan", kh: "បាកាន" },
        communes: [
          { en: "Beung Bat Kandal", kh: "បឹងបត់កណ្ដាល" },
          { en: "Beung Khnaer", kh: "បឹងខ្នារ" },
          { en: "Khnaer Totung", kh: "ខ្នារទទឹង" },
          { en: "Meteuk", kh: "មេទឹក" },
          { en: "O Ta Pong", kh: "អូរតាប៉ោង" },
          { en: "Rumlech", kh: "រំលេច" },
          { en: "Snam Preah", kh: "ស្នាមព្រះ" },
          { en: "Svay Don Kaev", kh: "ស្វាយដូនកែវ" },
          { en: "Talo", kh: "តាលោ" },
          { en: "Trapeang Jong", kh: "ត្រពាំងជង" },
        ],
      },
      {
        district: { en: "Kandieng", kh: "កណ្ដៀង" },
        communes: [
          { en: "Anlong Vil", kh: "អន្លង់វិល" },
          { en: "Kandieng", kh: "កណ្ដៀង" },
          { en: "Kanjor", kh: "កញ្ចរ" },
          { en: "Koh Jum", kh: "កោះជុំ" },
          { en: "Reang Til", kh: "រាំងទិល" },
          { en: "Srae Stok", kh: "ស្រែស្ដុក" },
          { en: "Svay Luong", kh: "ស្វាយលួង" },
          { en: "Sya", kh: "ស្យា" },
          { en: "Veal", kh: "វាល" },
        ],
      },
      {
        district: { en: "Krakor", kh: "ក្រគរ" },
        communes: [
          { en: "Anlong Tnot", kh: "អន្លង់ត្នោត" },
          { en: "Ansa Chambaek", kh: "អន្សាចំបក់" },
          { en: "Beung Kantuot", kh: "បឹងកន្ទួត" },
          { en: "Chher Tum", kh: "ឈើតុំ" },
          { en: "Kampong Hluong", kh: "កំពង់ហ្លួង" },
          { en: "Kampong Pouth", kh: "កំពង់ពោធិ៍" },
          { en: "Kbal Trach", kh: "ក្បាលត្រាច" },
          { en: "O Rasand", kh: "អូរសណ្ដាន់" },
          { en: "Sna Ansa", kh: "ស្នាអន្សា" },
          { en: "Svay S", kh: "ស្វាយស" },
          { en: "Tnot Jum", kh: "ត្នោតជុំ" },
        ],
      },
      {
        district: { en: "Puth Sat", kh: "ពោធិ៍សាត់" },
        communes: [
          { en: "Banteay Dei", kh: "បន្ទាយដី" },
          { en: "Chamroun Phal", kh: "ចំរើនផល" },
          { en: "Lolak", kh: "លលកស" },
          { en: "Pheakthas Prey", kh: "ផ្ទះព្រៃ" },
          { en: "Prey Nhi", kh: "ព្រៃញី" },
          { en: "Rolab", kh: "រលាប" },
          { en: "Svay At", kh: "ស្វាយអាត់" },
        ],
      },
      {
        district: { en: "Phnum Kravanh", kh: "ភ្នំក្រវ៉ាញ" },
        communes: [
          { en: "Bak Chinchan", kh: "បាក់ចិញ្ចៀន" },
          { en: "Lach", kh: "លាច" },
          { en: "Pheakthas Rung", kh: "ផ្ទះរុង" },
          { en: "Prangil", kh: "ព្រងិល" },
          { en: "Rakat", kh: "រកាត" },
          { en: "Samrong", kh: "សំរោង" },
          { en: "Santrai", kh: "សន្ទ្រែ" },
        ],
      },
      {
        district: { en: "Veal Veng", kh: "វាលវែង" },
        communes: [
          { en: "Anlong Reab", kh: "អន្លង់រាប" },
          { en: "Krapeu Pi", kh: "ក្រពើពីរ" },
          { en: "O Rasom", kh: "អូរសោម" },
          { en: "Bramoy", kh: "ប្រម៉ោយ" },
          { en: "Thma Da", kh: "ថ្មដា" },
        ],
      },
    ],
  },
];
