const car = [
  {
    brandName: "MG",
    model: [
      "3",
      "5EV",
      "6",
      "7",
      "GS",
      "GT",
      "Hector",
      "HS",
      "HS Plug-In",
      "Marvel R",
      "RX5",
      "RX8",
      "160",
      "ZS",
      "ZS EV",
      "ZST",
      "Other",
    ],
  },

  {
    brandName: "JETOUR",
    model: ["DASHING", "T2", "X70", "X90", "X95", "Other"],
  },
  {
    brandName: "Toyota",
    model: [
      "Camry",
      "Prius",
      "Raize",
      "Alphard",
      "BZ4x",
      "Corolla",
      "Fortuner",
      "Hiace",
      "Highlander",
      "Hilux Rally",
      "Hilux REVO",
      "Hilux Vigo",
      "Land Cruiser",
      "Land Cruiser PRADO",
      "RAV4",
      "Scion",
      "Sienna",
      "Tacoma",
      "Tundra",
      "Vitz",
      "Yaris",
      "4Runner",
      "Celica",
      "Rush",
      "86",
      "Aristo",
      "Aurion",
      "Avalon",
      "Avenza",
      "Aygo",
      "Belta",
      "BZ3",
      "C-HR",
      "Camry Vienta",
      "Coaster",
      "Corolla Altis",
      "Corolla CROSS",
      "Corona Avante",
      "Cressida",
      "Crown",
      "Dyna",
    ],
  },

  {
    brandName: "Lexus",
    model: [
      "RX200T",
      "RX300",
      "RX330",
      "RX400h",
      "RX450h",
      "LX450d",
      "LX470",
      "LX570",
      "LX600",
      "CT",
      "ES",
      "GS",
      "GX",
      "HS",
      "IS",
      "IS F",
      "LC",
      "LFA",
      "LS",
      "LX450",
      "LX500d",
      "NX",
      "RC",
      "RX350L",
      "RX450HL",
      "RX500h",
      "RZ450e",
      "SC",
      "UX",
      "Other - ផ្សេងៗ",
    ],
  },

  {
    brandName: "Lexus",
    model: [
      "RX200T",
      "RX300",
      "RX330",
      "RX400h",
      "RX450h",
      "LX450d",
      "LX470",
      "LX570",
      "LX600",
      "CT",
      "ES",
      "GS",
      "GX",
      "HS",
      "IS",
      "IS F",
      "LC",
      "LFA",
      "LS",
      "LX450",
      "LX500d",
      "NX",
      "RC",
      "RX350L",
      "RX450HL",
      "RX500h",
      "RZ450e",
      "SC",
      "UX",
      "Other - ផ្សេងៗ",
    ],
  },
  {
    brandName: "Mazda",
    model: [
      "BT50",
      "BT50 Pro",
      "CX-5",
      "Mazda2",
      "Mazda6",
      "323",
      "626",
      "929",
      "B-Series",
      "B-Series Plus",
      "B2000",
      "B2500",
      "B2600",
      "Bongo",
      "Bongo Brawny",
      "Cx-3",
      "Cx-4",
      "CX-60",
      "CX-7",
      "CX-8",
      "CX-9",
      "CX-90",
      "Eclipse",
      "EZ-6",
      "Familia Van",
      "GLC",
      "Mazda3",
      "Mazda5",
      "Mazda6 5-Door",
      "Mazda6 Sport",
      "Mazdaspeed 3",
      "Mazdaspeed 6",
      "Miata MX-5",
      "Millenia",
      "MPV",
      "MX-3",
      "Mx-30",
      "Mx-5",
      "Mx-6",
    ],
  },

  {
    brandName: "Hyundai",
    model: [
      "Tourism - ទូរីស",
      "Truck - ឡានដឹក",
      "Accent",
      "Atoz",
      "Aura",
      "Avante",
      "Azera",
      "County",
      "Creta",
      "Elantra",
      "Elite i20",
      "Entourage",
      "Eon",
      "Equus",
      "Excel",
      "Genesis",
      "Genesis Coupe",
    ],
  },
];
